# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .api_key_calls_scope_permission import ApiKeyCallsScopePermission
from .api_key_scope_permission import ApiKeyScopePermission


class ApiKey(UniversalBaseModel):
    """
    API key details including IP restrictions and scope permissions.
    """

    id: int = pydantic.Field()
    """
    API key ID.
    """

    label: str = pydantic.Field()
    """
    API key label.
    """

    value: str = pydantic.Field()
    """
    API key value.
    """

    active: bool = pydantic.Field()
    """
    Indicates whether the API key is active.
    """

    restricted: bool = pydantic.Field()
    """
    Indicates whether IP restrictions are enabled. When enabled,
     the API key works only from IP addresses in `permitted_ips`.
    """

    permitted_ips: typing.List[str] = pydantic.Field()
    """
    List of permitted IP addresses. If `restricted` is false,
     an empty list means no IP restrictions. If `restricted` is true,
      an empty list prevents all requests.
    """

    scopes_enabled: bool = pydantic.Field()
    """
    When `true`, the key is restricted to the permissions defined in the
    scope fields below. When `false`, the key has full access.
    """

    last_used_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Timestamp of the most recent authenticated request made with this key.
    """

    numbers: typing.Optional[ApiKeyScopePermission] = pydantic.Field(default=None)
    """
    View, buy, release, and configure phone numbers, browse inventory, and manage the cart.
    """

    trunks: typing.Optional[ApiKeyScopePermission] = pydantic.Field(default=None)
    """
    View, create, update, and delete SIP trunks and their settings.
    """

    calls: typing.Optional[ApiKeyCallsScopePermission] = pydantic.Field(default=None)
    """
    Access call records and active calls, and control live call actions such as starting, answering, ending, audio playback, DTMF, streaming, and transcription requests.
    """

    messages: typing.Optional[ApiKeyScopePermission] = pydantic.Field(default=None)
    """
    Access message history and Sender IDs, send messages, manage opt-outs, and create or delete Sender IDs.
    """

    recordings: typing.Optional[ApiKeyScopePermission] = pydantic.Field(default=None)
    """
    List, download, and delete call recordings.
    """

    campaigns: typing.Optional[ApiKeyScopePermission] = pydantic.Field(default=None)
    """
    View campaign analytics and Sender ID or Brand status, schedule bulk voice or SMS campaigns, register Brands, and create short links.
    """

    two_fa: typing.Optional[ApiKeyScopePermission] = pydantic.Field(default=None)
    """
    View 2FA service details and verification logs, trigger OTPs by voice or SMS, and validate verification codes.
    """

    validator: typing.Optional[ApiKeyScopePermission] = pydantic.Field(default=None)
    """
    View number validation results and trigger single or bulk validation or HLR lookup requests.
    """

    webhooks: typing.Optional[ApiKeyScopePermission] = pydantic.Field(default=None)
    """
    List, create, and delete webhooks.
    """

    embeddable: typing.Optional[ApiKeyScopePermission] = pydantic.Field(default=None)
    """
    Manage widget tokens, including listing, viewing, creating, updating, and deleting them.
    """

    billing: typing.Optional[ApiKeyScopePermission] = pydantic.Field(default=None)
    """
    Access statements, balance, payment methods, usage reports, and billing settings, including payment method updates.
    """

    account: typing.Optional[ApiKeyScopePermission] = pydantic.Field(default=None)
    """
    View and update account profile information and timezone.
    """

    subaccounts: typing.Optional[ApiKeyScopePermission] = pydantic.Field(default=None)
    """
    Manage subaccounts: list and view them, create, update, and suspend them.
    """

    created_at: dt.datetime = pydantic.Field()
    """
    Creation date and time in ISO 8601 format.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
