# This file was auto-generated by Fern from our API Definition.

from .api_key import ApiKey

ApiKeyWithSecret = ApiKey
"""
API key details, including the secret `value`. Returned only at creation time —
store it securely, it cannot be retrieved again.
"""
