# This file was auto-generated by Fern from our API Definition.

import typing

from .call_webhook_list_response_item import CallWebhookListResponseItem

CallWebhookListResponse = typing.List[CallWebhookListResponseItem]
"""
List of call webhooks configured for the phone number.
"""
