# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .call_create_response_event_type import CallCreateResponseEventType
from .call_direction import CallDirection
from .on_call_event_payload import OnCallEventPayload


class CallCreateResponse(UniversalBaseModel):
    uuid_: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="uuid"),
        pydantic.Field(alias="uuid", description="Call ID. Deprecated — use `id` instead."),
    ] = None
    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Call ID. Alias of `uuid`.
    """

    direction: typing.Optional[CallDirection] = None
    event_type: typing.Optional[CallCreateResponseEventType] = pydantic.Field(default=None)
    """
    Most recent lifecycle event for the call. One of:
    
    - `call_setup` — the call is being initiated.
    - `ringing` — the destination is ringing.
    - `early_media` — early media (such as ringback) is playing before answer.
    - `answered` — the destination answered the call.
    - `completed` — the call ended normally.
    - `busy` — the destination was busy.
    - `cancelled` — the call was cancelled before answer.
    - `rejected` — the destination rejected the call.
    - `on_call_event` — an in-call event occurred (see `event_payload`).
    """

    event_time: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Date and time of the latest event
    """

    event_payload: typing.Optional[OnCallEventPayload] = pydantic.Field(default=None)
    """
    Event-specific data
    """

    from_: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="from"), pydantic.Field(alias="from", description="Caller ID")
    ] = None
    to: typing.Optional[str] = pydantic.Field(default=None)
    """
    Destination number
    """

    call_started: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Date and time when the call started
    """

    call_answered: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Date and time when the call was answered
    """

    call_completed: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Date and time when the call ended
    """

    machine_detected: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Indicates whether the call was answered by an answering machine
    """

    tag: typing.Optional[str] = pydantic.Field(default=None)
    """
    Call metadata
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
