# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .call_disposition import CallDisposition


class Cdr(UniversalBaseModel):
    """
    Call detail record (CDR) for an individual call.
    """

    date: dt.datetime = pydantic.Field()
    """
    Date and time of the call in ISO 8601 format.
    """

    from_: typing_extensions.Annotated[
        str, FieldMetadata(alias="from"), pydantic.Field(alias="from", description="Originating phone number (ANI).")
    ]
    to: str = pydantic.Field()
    """
    Destination phone number (DNIS).
    """

    disposition: CallDisposition
    duration: int = pydantic.Field()
    """
    Call duration in seconds.
    """

    destination: str = pydantic.Field()
    """
    Destination of the call. For outbound calls,
     contains the country name and, optionally, a mobile carrier
      or city name. For inbound calls, includes the SIP trunk name,
       SIP URI, or PSTN number the call is forwarded to.
    """

    per_minute: str = pydantic.Field()
    """
    Price per minute in USD.
    """

    charge: str = pydantic.Field()
    """
    Total charge for the call in USD.
    """

    sip_trunk: typing.Optional[str] = pydantic.Field(default=None)
    """
    System-generated SIP trunk login. For outbound calls only.
    """

    forward_fee: typing.Optional[str] = pydantic.Field(default=None)
    """
    PSTN forwarding price in USD. For inbound calls only when forwarded to PSTN.
    """

    uuid_: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="uuid"),
        pydantic.Field(alias="uuid", description="Call ID. Deprecated — use `call_id` instead."),
    ]
    call_id: str = pydantic.Field()
    """
    Call ID. Alias of `uuid`.
    """

    parent_uuid: typing.Optional[str] = pydantic.Field(default=None)
    """
    Parent call ID. Deprecated — use `parent_call_id` instead.
    """

    parent_call_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Parent call ID. Alias of `parent_uuid`.
    """

    answered_by: typing.Optional[str] = pydantic.Field(default=None)
    """
    Who answered the call. Possible values are `human`, `machine`.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
