# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .cdr_with_transcription import CdrWithTranscription
from .pagination import Pagination


class CdrTranscriptionSearchResponse(UniversalBaseModel):
    items: typing.List[CdrWithTranscription] = pydantic.Field()
    """
    List of CDRs with transcription links.
    """

    pagination: Pagination

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
