# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .invoice import Invoice
from .pagination import Pagination


class InvoiceListResponse(UniversalBaseModel):
    is_empty: bool = pydantic.Field()
    """
    Indicates whether the statement list is empty.
    """

    invoices: typing.List[Invoice] = pydantic.Field()
    """
    Auto-generated statements for the account.
    """

    pagination: Pagination

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
