# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .message_delivery_status import MessageDeliveryStatus


class MessagesDeliveryReport(UniversalBaseModel):
    """
    Message delivery report (DLR).
    """

    message_id: str = pydantic.Field()
    """
    Message ID.
    """

    message_type: str = pydantic.Field()
    """
    Type of message. Possible values are `sms`, `mms`.
    """

    from_: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="from"),
        pydantic.Field(alias="from", description="Sender ID. Can be numeric or alphanumeric."),
    ]
    to: str = pydantic.Field()
    """
    Destination phone number.
    """

    tag: typing.Optional[str] = pydantic.Field(default=None)
    """
    Tag to identify a group of messages, such as those associated with a campaign.
    """

    status: MessageDeliveryStatus
    segments_count: int = pydantic.Field()
    """
    Number of message segments for SMS. For MMS, the value is always 1.
    """

    sent: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Date and time the message was accepted in ISO 8601 format.
    """

    delivered: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Date and time when the final status was received in ISO 8601 format.
    """

    error: typing.Optional[str] = pydantic.Field(default=None)
    """
    Human-readable error description.
    """

    charge: str = pydantic.Field()
    """
    Total charge for the message in USD.
    """

    carrier_fees: str = pydantic.Field()
    """
    Mobile carrier fees in USD.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
