# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .document_type_info import DocumentTypeInfo
from .number import Number
from .pagination import Pagination


class NumberListResponse(UniversalBaseModel):
    items: typing.List[Number] = pydantic.Field()
    """
    List of phone numbers on the account.
    """

    doc_types: typing.List[DocumentTypeInfo] = pydantic.Field()
    """
    Documents required to activate phone numbers.
    """

    pagination: Pagination

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
