# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class PhoneValidationResponse(UniversalBaseModel):
    phone_number: str = pydantic.Field()
    """
    Phone number.
    """

    valid: bool = pydantic.Field()
    """
    Indicates whether the phone number is valid.
    """

    country_code: typing.Optional[str] = pydantic.Field(default=None)
    """
    ISO 3166-1 alpha-2 country code of the phone number.
     `null` if the number is invalid.
    """

    e164format: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="e164_format"),
        pydantic.Field(alias="e164_format", description="Phone number in international E.164 format."),
    ]
    national_format: str = pydantic.Field()
    """
    Phone number in the national format of the identified country.
    """

    ported: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Indicates whether the phone number was ported or not. `null` if the phone number is invalid.
    """

    mcc: typing.Optional[str] = pydantic.Field(default=None)
    """
    Mobile Country Code of the phone number carrier. For mobile phone numbers only. `null` if the phone number is invalid.
    """

    mnc: typing.Optional[str] = pydantic.Field(default=None)
    """
    Mobile Network Code of the phone number carrier. For mobile phone numbers only. `null` if the phone number is invalid
    """

    number_type: typing.Optional[str] = pydantic.Field(default=None)
    """
    Number type. Possible values are `mobile`, `landline`, or `toll-free`. `null` if the phone number is invalid.
    """

    carrier_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Name of the phone number carrier. `null` if the phone number is invalid.
    """

    risky_destination: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Indicates whether the phone number belongs to a number range associated with traffic pumping. `null` if the number is invalid.
    """

    unallocated_range: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Indicates whether the phone number belongs to an unallocated number range. `null` if the number is invalid
    """

    reachable: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Indicates whether the number is registered in a mobile network. For mobile phone numbers only. `null` if the number is invalid
    """

    roaming: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Indicates whether the number is roaming. For mobile phone numbers only. `null` if the number is invalid
    """

    timezone: typing.Optional[str] = pydantic.Field(default=None)
    """
    Time zone based on the phone number's country and area code.
     `null` if the number is invalid.
    """

    charge: str = pydantic.Field()
    """
    Charge for the validation.
    """

    error_code: str = pydantic.Field()
    """
    Error code for the request. `000` indicates success.
    Possible values:
    - `013`: — Internal service error
    - `021`: — Invalid phone number length or format
    - `041`: — Request timeout
    - `042`: — Request failed
    - `091`: — Insufficient funds
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
