# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .profile_response_company_info_country import ProfileResponseCompanyInfoCountry
from .profile_response_company_info_industry import ProfileResponseCompanyInfoIndustry


class ProfileResponseCompanyInfo(UniversalBaseModel):
    """
    Company details.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Company name.
    """

    industry: typing.Optional[ProfileResponseCompanyInfoIndustry] = pydantic.Field(default=None)
    """
    Industry the company operates in. One of `telecommunications`, `information technology and services`, `fintech and finance`, `healthcare and pharmaceuticals`, `ecommerce and retail`, `education and research`, `pickup and delivery`, `transportation and logistics`, `media and entertainment`, `travel and hospitality`, `non-profit and charity organizations`, `manufacturing and industrial goods`, or `other`. Each value names the company's sector. `null` when the industry is not set.
    """

    address: typing.Optional[str] = pydantic.Field(default=None)
    """
    Company address.
    """

    attn_contact_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Billing contact name.
    """

    vat_number: typing.Optional[str] = pydantic.Field(default=None)
    """
    VAT number.
    """

    country: typing.Optional[ProfileResponseCompanyInfoCountry] = pydantic.Field(default=None)
    """
    Country.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
