# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .sender_id_response_type import SenderIdResponseType


class SenderIdResponse(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    Sender ID ID.
    """

    sender_id: str = pydantic.Field()
    """
    Sender ID.
    """

    type: SenderIdResponseType = pydantic.Field()
    """
    Format of the Sender ID. One of `alphanumeric` (a text sender name), `numeric` (a phone number), or `shortcode` (a short code).
    """

    usecase: typing.Optional[str] = pydantic.Field(default=None)
    """
    Use case for the Sender ID.
    """

    samples: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Message samples.
    """

    allowlisted_in: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    List of countries where the Sender ID is allowlisted.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
