# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class SubAccountsTransactionsListResponseTransactionsItem(UniversalBaseModel):
    amount: typing.Optional[float] = pydantic.Field(default=None)
    """
    Transaction amount.
    """

    balance_after: typing.Optional[float] = pydantic.Field(default=None)
    """
    Sub-account balance after the transaction.
    """

    date: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Transaction date and time in ISO 8601 format.
    """

    details: typing.Optional[str] = pydantic.Field(default=None)
    """
    Transaction details.
    """

    status: typing.Optional[str] = pydantic.Field(default=None)
    """
    Transaction status.
    """

    type: typing.Optional[int] = pydantic.Field(default=None)
    """
    Transaction type.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
