# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .ten_dlc_brand import TenDlcBrand
from .ten_dlc_brand_list_response_pagination import TenDlcBrandListResponsePagination


class TenDlcBrandListResponse(UniversalBaseModel):
    """
    A list of 10DLC Brands
    """

    items: typing.List[TenDlcBrand] = pydantic.Field()
    """
    A paginated list of 10DLC Brands matching the filter criteria
    """

    pagination: TenDlcBrandListResponsePagination = pydantic.Field()
    """
    Pagination details
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
