# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .ten_dlc_brand_entity_type import TenDlcBrandEntityType
from .ten_dlc_brand_identity_verification_status import TenDlcBrandIdentityVerificationStatus


class TenDlcBrand(UniversalBaseModel):
    """
    Represents a 10DLC brand registered for application-to-person messaging. A Brand identifies the business behind one or more messaging campaigns.
    """

    brand_id: str = pydantic.Field()
    """
    Unique identifier of the Brand assigned by the registry.
    """

    dba_name: str = pydantic.Field()
    """
    Doing-business-as name, or the public-facing brand name.
    """

    company_name: str = pydantic.Field()
    """
    Registered legal name of the company that owns the Brand.
    """

    entity_type: TenDlcBrandEntityType = pydantic.Field()
    """
    Company entity type.
    """

    vertical: str = pydantic.Field()
    """
    Industry vertical the Brand operates in.
    """

    ein_taxid: str = pydantic.Field()
    """
    IRS Employer Identification Number (EIN) or other tax ID of the company.
    """

    ein_taxid_country: str = pydantic.Field()
    """
    ISO 3166-1 alpha-2 country code where the Tax ID was issued.
    """

    status: TenDlcBrandIdentityVerificationStatus = pydantic.Field()
    """
    Brand identity verification status.
    """

    website: typing.Optional[str] = pydantic.Field(default=None)
    """
    Business website URL.
    """

    stock_symbol: typing.Optional[str] = pydantic.Field(default=None)
    """
    Stock ticker symbol of the company. Required for publicly traded companies.
    """

    stock_exchange: typing.Optional[str] = pydantic.Field(default=None)
    """
    Code of the stock exchange the company is listed on. Required for publicly traded companies.
    """

    first_name: str = pydantic.Field()
    """
    Business contact first name.
    """

    last_name: str = pydantic.Field()
    """
    Business contact last name.
    """

    phone_number: str = pydantic.Field()
    """
    Support contact phone number in E.164 format.
    """

    email: str = pydantic.Field()
    """
    Support contact email address.
    """

    street_address: str = pydantic.Field()
    """
    Street address of the business.
    """

    city: str = pydantic.Field()
    """
    City of the business address.
    """

    state_or_province: typing.Optional[str] = pydantic.Field(default=None)
    """
    State or province of the business address.
    """

    country: str = pydantic.Field()
    """
    ISO 3166-1 alpha-2 country code of the business address.
    """

    zip: str = pydantic.Field()
    """
    ZIP or postal code of the business address.
    """

    feedback: typing.Optional[str] = pydantic.Field(default=None)
    """
    Feedback from the identity verification process explaining the current `status`.
    """

    mock: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Indicates whether the Brand is a mock brand for testing.
    """

    created_at: str = pydantic.Field()
    """
    Timestamp when the Brand was created, in ISO 8601 format.
    """

    updated_at: str = pydantic.Field()
    """
    Timestamp when the Brand was last updated, in ISO 8601 format.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
