# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .ten_dlc_brand_vetting_appeal_appeal_outcome_feedback import TenDlcBrandVettingAppealAppealOutcomeFeedback


class TenDlcBrandVettingAppealAppealOutcome(UniversalBaseModel):
    """
    Outcome of the appeal, including the revised vetting status and score.
    """

    vet_status: str = pydantic.Field()
    """
    Current status of the Brand vetting
    """

    vet_score: int = pydantic.Field()
    """
    The Brand vetting score
    """

    feedback: TenDlcBrandVettingAppealAppealOutcomeFeedback = pydantic.Field()
    """
    The feedback provided by the external vetting provider
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
