# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .ten_dlc_brand_create_request_zero_entity_type import TenDlcBrandCreateRequestZeroEntityType


class TenDlcBrandCreateRequestZero(UniversalBaseModel):
    """
    PUBLIC_PROFIT brands must provide stock_symbol and stock_exchange.
    """

    entity_type: typing.Optional[TenDlcBrandCreateRequestZeroEntityType] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
