# This file was auto-generated by Fern from our API Definition.

import typing

TenDlcBrandAppealCreateRequestAppealCategoriesItem = typing.Union[
    typing.Literal["VERIFY_TAX_ID", "VERIFY_NON_PROFIT", "VERIFY_GOVERNMENT"], typing.Any
]
