# This file was auto-generated by Fern from our API Definition.

import typing

TtsVoiceId = typing.Union[
    typing.Literal[
        "Ivy",
        "Joanna",
        "Kendra",
        "Kimberly",
        "Salli",
        "Joey",
        "Justin",
        "Matthew",
        "Conchita",
        "Lucia",
        "Enrique",
        "Marlene",
        "Vicki",
        "Hans",
        "Tatyana",
        "Maxim",
    ],
    typing.Any,
]
