# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class UnprocessableEntityErrorBody(UniversalBaseModel):
    error: typing.Optional[str] = pydantic.Field(default=None)
    """
    Human-readable error description.
    """

    error_dids: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Numbers from the cart that could not be purchased.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
