# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .whats_app_message_send_request_template_buttons_item_type import WhatsAppMessageSendRequestTemplateButtonsItemType


class WhatsAppMessageSendRequestTemplateButtonsItem(UniversalBaseModel):
    type: WhatsAppMessageSendRequestTemplateButtonsItemType

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
