# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .whats_app_problem_error_class import WhatsAppProblemErrorClass


class WhatsAppProblem(UniversalBaseModel):
    """
    RFC 9457 problem document returned by WhatsApp endpoints as `application/problem+json`.
    """

    type: str = pydantic.Field()
    """
    URI identifying the problem type.
    """

    title: str = pydantic.Field()
    """
    Short, human-readable summary of the problem type.
    """

    status: int = pydantic.Field()
    """
    HTTP status code.
    """

    detail: str = pydantic.Field()
    """
    Human-readable explanation specific to this occurrence of the problem.
    """

    instance: str = pydantic.Field()
    """
    URI identifying this specific occurrence of the problem, such as the request ID.
    """

    error_class: typing.Optional[WhatsAppProblemErrorClass] = pydantic.Field(default=None)
    """
    Machine-readable classification of the error.
    """

    error_code: typing.Optional[str] = pydantic.Field(default=None)
    """
    Stable machine-readable error code, derived from the problem slug.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
