# This file was auto-generated by Fern from our API Definition.

import typing

WhatsAppSenderStatus = typing.Union[
    typing.Literal[
        "banned",
        "connected",
        "deleted",
        "disconnected",
        "flagged",
        "migrated",
        "pending",
        "rate_limited",
        "restricted",
        "unknown",
        "unverified",
    ],
    typing.Any,
]
