# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .whats_app_message_send_request_template_header_type import WhatsAppMessageSendRequestTemplateHeaderType


class WhatsAppMessageSendRequestTemplateHeader(UniversalBaseModel):
    """
    Header content, required only when the template's `HEADER` component needs one.
    """

    type: typing.Optional[WhatsAppMessageSendRequestTemplateHeaderType] = None
    placeholder: typing.Optional[str] = pydantic.Field(default=None)
    """
    Value for a `TEXT` header's `{{1}}` placeholder.
    """

    media_url: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="mediaUrl"),
        pydantic.Field(alias="mediaUrl", description="Media URL for an `IMAGE`/`VIDEO`/`DOCUMENT` header."),
    ] = None
    filename: typing.Optional[str] = pydantic.Field(default=None)
    """
    Filename for a `DOCUMENT` header.
    """

    latitude: typing.Optional[float] = pydantic.Field(default=None)
    """
    Latitude for a `LOCATION` header.
    """

    longitude: typing.Optional[float] = pydantic.Field(default=None)
    """
    Longitude for a `LOCATION` header.
    """

    parameter_name: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="parameterName"),
        pydantic.Field(alias="parameterName", description="Placeholder name for a named-parameter `TEXT` header."),
    ] = None
    text: typing.Optional[str] = pydantic.Field(default=None)
    """
    Value for a named-parameter `TEXT` header.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
