# This file was auto-generated by Fern from our API Definition.

import typing

WhatsAppTemplateStatus = typing.Union[
    typing.Literal[
        "draft",
        "pending",
        "approved",
        "rejected",
        "paused",
        "flagged",
        "disabled",
        "in_appeal",
        "pending_deletion",
        "deleted",
        "unknown",
    ],
    typing.Any,
]
