# This file was auto-generated by Fern from our API Definition.

import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from ...types.call_stream_channel import CallStreamChannel
from ...types.call_stream_response import CallStreamResponse
from ...types.call_stream_type import CallStreamType
from ...types.success_response import SuccessResponse
from .raw_client import AsyncRawStreamsClient, RawStreamsClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class StreamsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawStreamsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawStreamsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawStreamsClient
        """
        return self._raw_client

    def create(
        self,
        call_id: str,
        *,
        stream_url: str,
        stream_type: CallStreamType,
        stream_channel: CallStreamChannel,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CallStreamResponse:
        """
        Starts streaming the audio of the call identified by `call_id` to a WebSocket destination you supply, in the direction (`stream_type`) and channel (`stream_channel`) you configure. The destination can be any URL you specify — Wavix does not restrict it. Returns the `stream_id`.

        Parameters
        ----------
        call_id : str
            The `uuid` of the call.

        stream_url : str
            WebSocket URL for call streaming

        stream_type : CallStreamType
            Direction of audio streamed to `stream_url`.

        stream_channel : CallStreamChannel
            Audio channel streamed to `stream_url`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CallStreamResponse
            Returns the created media stream, including its `stream_id`.

        Examples
        --------
        from wavix import Wavix

        client = Wavix(
            token="YOUR_TOKEN",
        )
        client.call_control.streams.create(
            call_id="call_id",
            stream_url="wss://examples.com/stream",
            stream_type="oneway",
            stream_channel="inbound",
        )
        """
        _response = self._raw_client.create(
            call_id,
            stream_url=stream_url,
            stream_type=stream_type,
            stream_channel=stream_channel,
            request_options=request_options,
        )
        return _response.data

    def delete(
        self, call_id: str, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> SuccessResponse:
        """
        Stops the media stream identified by `id` on the call identified by `call_id`.

        Parameters
        ----------
        call_id : str
            The `uuid` of the call.

        id : str
            The `uuid` of the media stream to stop.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SuccessResponse
            Returns a success confirmation. The media stream is stopped.

        Examples
        --------
        from wavix import Wavix

        client = Wavix(
            token="YOUR_TOKEN",
        )
        client.call_control.streams.delete(
            call_id="call_id",
            id="id",
        )
        """
        _response = self._raw_client.delete(call_id, id, request_options=request_options)
        return _response.data


class AsyncStreamsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawStreamsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawStreamsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawStreamsClient
        """
        return self._raw_client

    async def create(
        self,
        call_id: str,
        *,
        stream_url: str,
        stream_type: CallStreamType,
        stream_channel: CallStreamChannel,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CallStreamResponse:
        """
        Starts streaming the audio of the call identified by `call_id` to a WebSocket destination you supply, in the direction (`stream_type`) and channel (`stream_channel`) you configure. The destination can be any URL you specify — Wavix does not restrict it. Returns the `stream_id`.

        Parameters
        ----------
        call_id : str
            The `uuid` of the call.

        stream_url : str
            WebSocket URL for call streaming

        stream_type : CallStreamType
            Direction of audio streamed to `stream_url`.

        stream_channel : CallStreamChannel
            Audio channel streamed to `stream_url`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CallStreamResponse
            Returns the created media stream, including its `stream_id`.

        Examples
        --------
        import asyncio

        from wavix import AsyncWavix

        client = AsyncWavix(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.call_control.streams.create(
                call_id="call_id",
                stream_url="wss://examples.com/stream",
                stream_type="oneway",
                stream_channel="inbound",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(
            call_id,
            stream_url=stream_url,
            stream_type=stream_type,
            stream_channel=stream_channel,
            request_options=request_options,
        )
        return _response.data

    async def delete(
        self, call_id: str, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> SuccessResponse:
        """
        Stops the media stream identified by `id` on the call identified by `call_id`.

        Parameters
        ----------
        call_id : str
            The `uuid` of the call.

        id : str
            The `uuid` of the media stream to stop.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SuccessResponse
            Returns a success confirmation. The media stream is stopped.

        Examples
        --------
        import asyncio

        from wavix import AsyncWavix

        client = AsyncWavix(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.call_control.streams.delete(
                call_id="call_id",
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(call_id, id, request_options=request_options)
        return _response.data
