# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ...core.api_error import ApiError
from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.http_response import AsyncHttpResponse, HttpResponse
from ...core.jsonable_encoder import encode_path_param
from ...core.parse_error import ParsingError
from ...core.pydantic_utilities import parse_obj_as
from ...core.request_options import RequestOptions
from ...errors.bad_request_error import BadRequestError
from ...errors.unauthorized_error import UnauthorizedError
from ...types.call_stream_channel import CallStreamChannel
from ...types.call_stream_response import CallStreamResponse
from ...types.call_stream_type import CallStreamType
from ...types.success_response import SuccessResponse
from ...types.unauthorized_error_response import UnauthorizedErrorResponse
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawStreamsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def create(
        self,
        call_id: str,
        *,
        stream_url: str,
        stream_type: CallStreamType,
        stream_channel: CallStreamChannel,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[CallStreamResponse]:
        """
        Starts streaming the media of the call identified by `call_id` to the configured destination. Returns the `stream_id`.

        Parameters
        ----------
        call_id : str
            The `uuid` of the call.

        stream_url : str
            WebSocket URL for call streaming

        stream_type : CallStreamType
            Direction of audio streamed to `stream_url`.

        stream_channel : CallStreamChannel
            Audio channel streamed to `stream_url`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[CallStreamResponse]
            Returns the created media stream, including its `stream_id`.
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/calls/{encode_path_param(call_id)}/streams",
            method="POST",
            json={
                "stream_url": stream_url,
                "stream_type": stream_type,
                "stream_channel": stream_channel,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CallStreamResponse,
                    parse_obj_as(
                        type_=CallStreamResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        UnauthorizedErrorResponse,
                        parse_obj_as(
                            type_=UnauthorizedErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def delete(
        self, call_id: str, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[SuccessResponse]:
        """
        Stops the media stream identified by `id` on the call identified by `call_id`.

        Parameters
        ----------
        call_id : str
            The `uuid` of the call.

        id : str
            The `uuid` of the media stream to stop.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[SuccessResponse]
            Returns a success confirmation. The media stream is stopped.
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/calls/{encode_path_param(call_id)}/streams/{encode_path_param(id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SuccessResponse,
                    parse_obj_as(
                        type_=SuccessResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        UnauthorizedErrorResponse,
                        parse_obj_as(
                            type_=UnauthorizedErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawStreamsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def create(
        self,
        call_id: str,
        *,
        stream_url: str,
        stream_type: CallStreamType,
        stream_channel: CallStreamChannel,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[CallStreamResponse]:
        """
        Starts streaming the media of the call identified by `call_id` to the configured destination. Returns the `stream_id`.

        Parameters
        ----------
        call_id : str
            The `uuid` of the call.

        stream_url : str
            WebSocket URL for call streaming

        stream_type : CallStreamType
            Direction of audio streamed to `stream_url`.

        stream_channel : CallStreamChannel
            Audio channel streamed to `stream_url`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[CallStreamResponse]
            Returns the created media stream, including its `stream_id`.
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/calls/{encode_path_param(call_id)}/streams",
            method="POST",
            json={
                "stream_url": stream_url,
                "stream_type": stream_type,
                "stream_channel": stream_channel,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CallStreamResponse,
                    parse_obj_as(
                        type_=CallStreamResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        UnauthorizedErrorResponse,
                        parse_obj_as(
                            type_=UnauthorizedErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def delete(
        self, call_id: str, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[SuccessResponse]:
        """
        Stops the media stream identified by `id` on the call identified by `call_id`.

        Parameters
        ----------
        call_id : str
            The `uuid` of the call.

        id : str
            The `uuid` of the media stream to stop.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[SuccessResponse]
            Returns a success confirmation. The media stream is stopped.
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/calls/{encode_path_param(call_id)}/streams/{encode_path_param(id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SuccessResponse,
                    parse_obj_as(
                        type_=SuccessResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        UnauthorizedErrorResponse,
                        parse_obj_as(
                            type_=UnauthorizedErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
