# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .types import (
        CreateBrandsResponse,
        CreateBrandsResponseEntityType,
        CreateBrandsResponseStatus,
        DeleteBrandsResponse,
        GetBrandsResponse,
        GetBrandsResponseEntityType,
        GetBrandsResponseStatus,
        ListBrandsResponse,
        ListBrandsResponsePagination,
        QualifyUsecaseBrandsRequestUseCase,
        QualifyUsecaseBrandsResponse,
        TenDlcBrandUpdateRequestEntityType,
        TenDlcBrandUpdateRequestVertical,
        UpdateBrandsResponse,
        UpdateBrandsResponseEntityType,
        UpdateBrandsResponseStatus,
    )
_dynamic_imports: typing.Dict[str, str] = {
    "CreateBrandsResponse": ".types",
    "CreateBrandsResponseEntityType": ".types",
    "CreateBrandsResponseStatus": ".types",
    "DeleteBrandsResponse": ".types",
    "GetBrandsResponse": ".types",
    "GetBrandsResponseEntityType": ".types",
    "GetBrandsResponseStatus": ".types",
    "ListBrandsResponse": ".types",
    "ListBrandsResponsePagination": ".types",
    "QualifyUsecaseBrandsRequestUseCase": ".types",
    "QualifyUsecaseBrandsResponse": ".types",
    "TenDlcBrandUpdateRequestEntityType": ".types",
    "TenDlcBrandUpdateRequestVertical": ".types",
    "UpdateBrandsResponse": ".types",
    "UpdateBrandsResponseEntityType": ".types",
    "UpdateBrandsResponseStatus": ".types",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "CreateBrandsResponse",
    "CreateBrandsResponseEntityType",
    "CreateBrandsResponseStatus",
    "DeleteBrandsResponse",
    "GetBrandsResponse",
    "GetBrandsResponseEntityType",
    "GetBrandsResponseStatus",
    "ListBrandsResponse",
    "ListBrandsResponsePagination",
    "QualifyUsecaseBrandsRequestUseCase",
    "QualifyUsecaseBrandsResponse",
    "TenDlcBrandUpdateRequestEntityType",
    "TenDlcBrandUpdateRequestVertical",
    "UpdateBrandsResponse",
    "UpdateBrandsResponseEntityType",
    "UpdateBrandsResponseStatus",
]
