# This file was auto-generated by Fern from our API Definition.

import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from ...types.ten_dlc_brand_create_request import TenDlcBrandCreateRequest
from .raw_client import AsyncRawBrandsClient, RawBrandsClient
from .types.create_brands_response import CreateBrandsResponse
from .types.delete_brands_response import DeleteBrandsResponse
from .types.get_brands_response import GetBrandsResponse
from .types.list_brands_response import ListBrandsResponse
from .types.qualify_usecase_brands_request_use_case import QualifyUsecaseBrandsRequestUseCase
from .types.qualify_usecase_brands_response import QualifyUsecaseBrandsResponse
from .types.ten_dlc_brand_update_request_entity_type import TenDlcBrandUpdateRequestEntityType
from .types.ten_dlc_brand_update_request_vertical import TenDlcBrandUpdateRequestVertical
from .types.update_brands_response import UpdateBrandsResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class BrandsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawBrandsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawBrandsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawBrandsClient
        """
        return self._raw_client

    def list(
        self,
        *,
        dba_name: typing.Optional[str] = None,
        company_name: typing.Optional[str] = None,
        entity_type: typing.Optional[str] = None,
        status: typing.Optional[str] = None,
        country: typing.Optional[str] = None,
        show_deleted: typing.Optional[bool] = None,
        ein_taxid: typing.Optional[str] = None,
        mock: typing.Optional[bool] = None,
        created_before: typing.Optional[str] = None,
        created_after: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        per_page: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListBrandsResponse:
        """
        Returns a paginated list of 10DLC Brands for the authenticated account, filtered by date, name, legal name, and status.

        Parameters
        ----------
        dba_name : typing.Optional[str]
            Filters Brands by `dba_name` (doing-business-as name). Matches partial values.

        company_name : typing.Optional[str]
            Filters Brands by `company_name` (registered legal name). Matches partial values.

        entity_type : typing.Optional[str]
            Filters Brands by business entity type, such as `PRIVATE_PROFIT`.

        status : typing.Optional[str]
            Filters Brands by identity verification status, such as `VERIFIED`.

        country : typing.Optional[str]
            Filters Brands by registration country, as an ISO 3166-1 alpha-2 code (e.g., `US`).

        show_deleted : typing.Optional[bool]
            When `true`, includes deleted Brands in the results. Default `false`.

        ein_taxid : typing.Optional[str]
            Filters Brands by their Employer Identification Number (EIN) or tax ID.

        mock : typing.Optional[bool]
            When `true`, returns only mock Brands used for testing. Default `false`.

        created_before : typing.Optional[str]
            Returns brands created on or before this date, in `YYYY-MM-DD` format.

        created_after : typing.Optional[str]
            Returns brands created on or after this date, in `YYYY-MM-DD` format.

        page : typing.Optional[int]
            Page number to retrieve. Default `1`.

        per_page : typing.Optional[int]
            Number of records to return per page. Default `25`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListBrandsResponse
            Returns a paginated list of 10DLC Brands.

        Examples
        --------
        from wavix import Wavix

        client = Wavix(
            token="YOUR_TOKEN",
        )
        client.ten_dlc.brands.list(
            dba_name="Brand",
            company_name="Company",
            entity_type="PRIVATE_PROFIT",
            status="VERIFIED",
            country="US",
            show_deleted=False,
            ein_taxid="999999999",
            mock=False,
            created_before="2024-08-22",
            created_after="2024-08-22",
            page=1,
            per_page=25,
        )
        """
        _response = self._raw_client.list(
            dba_name=dba_name,
            company_name=company_name,
            entity_type=entity_type,
            status=status,
            country=country,
            show_deleted=show_deleted,
            ein_taxid=ein_taxid,
            mock=mock,
            created_before=created_before,
            created_after=created_after,
            page=page,
            per_page=per_page,
            request_options=request_options,
        )
        return _response.data

    def create(
        self, *, request: TenDlcBrandCreateRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> CreateBrandsResponse:
        """
        Registers a 10DLC Brand. TCR automatically verifies the brand identity. Only brands with `VERIFIED` or `VETTED_VERIFIED` identity status can register 10DLC Campaigns.

        Parameters
        ----------
        request : TenDlcBrandCreateRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateBrandsResponse
            Returns the registered 10DLC Brand.

        Examples
        --------
        from wavix import TenDlcBrandCreateRequestZero, Wavix

        client = Wavix(
            token="YOUR_TOKEN",
        )
        client.ten_dlc.brands.create(
            request=TenDlcBrandCreateRequestZero(),
        )
        """
        _response = self._raw_client.create(request=request, request_options=request_options)
        return _response.data

    def get(self, brand_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> GetBrandsResponse:
        """
        Returns the 10DLC Brand identified by `brand_id`.

        Parameters
        ----------
        brand_id : str
            The unique ID of the 10DLC Brand.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetBrandsResponse
            Returns the 10DLC Brand.

        Examples
        --------
        from wavix import Wavix

        client = Wavix(
            token="YOUR_TOKEN",
        )
        client.ten_dlc.brands.get(
            brand_id="BM20QP9",
        )
        """
        _response = self._raw_client.get(brand_id, request_options=request_options)
        return _response.data

    def update(
        self,
        brand_id: str,
        *,
        dba_name: typing.Optional[str] = OMIT,
        company_name: typing.Optional[str] = OMIT,
        entity_type: typing.Optional[TenDlcBrandUpdateRequestEntityType] = OMIT,
        vertical: typing.Optional[TenDlcBrandUpdateRequestVertical] = OMIT,
        ein_taxid: typing.Optional[str] = OMIT,
        ein_taxid_country: typing.Optional[str] = OMIT,
        website: typing.Optional[str] = OMIT,
        stock_symbol: typing.Optional[str] = OMIT,
        stock_exchange: typing.Optional[str] = OMIT,
        first_name: typing.Optional[str] = OMIT,
        last_name: typing.Optional[str] = OMIT,
        phone_number: typing.Optional[str] = OMIT,
        email: typing.Optional[str] = OMIT,
        street_address: typing.Optional[str] = OMIT,
        city: typing.Optional[str] = OMIT,
        state_or_province: typing.Optional[str] = OMIT,
        zip: typing.Optional[str] = OMIT,
        country: typing.Optional[str] = OMIT,
        mock: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UpdateBrandsResponse:
        """
        Updates the 10DLC Brand identified by `brand_id`. Changing identity fields, including `ein_taxid`, `ein_taxid_country`, and `entity_type`, resets the Brand status to `UNVERIFIED` and triggers automatic re-submission. Brands in `VETTED_VERIFIED` status or with active Campaigns cannot be updated.

        Parameters
        ----------
        brand_id : str
            The unique ID of the 10DLC Brand.

        dba_name : typing.Optional[str]
            Brand name or DBA

        company_name : typing.Optional[str]
            Legal name of the company

        entity_type : typing.Optional[TenDlcBrandUpdateRequestEntityType]
            Legal entity type of the company. One of `PRIVATE_PROFIT` (privately held for-profit company), `PUBLIC_PROFIT` (publicly traded for-profit company), `NON_PROFIT` (non-profit organization), or `GOVERNMENT` (government entity).

        vertical : typing.Optional[TenDlcBrandUpdateRequestVertical]
            Business segment the Brand operates in. One of:

            - `HEALTHCARE` — healthcare.
            - `PROFESSIONAL` — professional services.
            - `RETAIL` — retail.
            - `TECHNOLOGY` — technology.
            - `EDUCATION` — education.
            - `FINANCIAL` — financial services.
            - `NON_PROFIT` — non-profit organizations.
            - `GOVERNMENT` — government entities.
            - `OTHER` — any segment not listed above.

        ein_taxid : typing.Optional[str]
            IRS Employee Identification Number (EIN) for US-based or foreign companies with EIN. The numeric portion of Tax ID for companies incorporated in other countries.

        ein_taxid_country : typing.Optional[str]
            2-letter ISO country code of the Tax ID issuing country

        website : typing.Optional[str]
            The website of the business

        stock_symbol : typing.Optional[str]
            The stock symbol of the Brand. For PUBLIC_PROFIT Brands only.

        stock_exchange : typing.Optional[str]
            The stock exchange code. For PUBLIC_PROFIT Brands only.

        first_name : typing.Optional[str]
            The first name of the business contact

        last_name : typing.Optional[str]
            The last name of the business contact

        phone_number : typing.Optional[str]
            The support contact telephone in E.164 format

        email : typing.Optional[str]
            The email address of the support contact

        street_address : typing.Optional[str]
            Street name and house number

        city : typing.Optional[str]
            The city name

        state_or_province : typing.Optional[str]
            State or province. For the United States, use 2 character codes.

        zip : typing.Optional[str]
            The business zip or postal code

        country : typing.Optional[str]
            2-letter ISO country code the business address

        mock : typing.Optional[bool]
            Mock flag for testing (optional, defaults to false)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdateBrandsResponse
            Returns the updated 10DLC Brand.

        Examples
        --------
        from wavix import Wavix

        client = Wavix(
            token="YOUR_TOKEN",
        )
        client.ten_dlc.brands.update(
            brand_id="BM20QP9",
        )
        """
        _response = self._raw_client.update(
            brand_id,
            dba_name=dba_name,
            company_name=company_name,
            entity_type=entity_type,
            vertical=vertical,
            ein_taxid=ein_taxid,
            ein_taxid_country=ein_taxid_country,
            website=website,
            stock_symbol=stock_symbol,
            stock_exchange=stock_exchange,
            first_name=first_name,
            last_name=last_name,
            phone_number=phone_number,
            email=email,
            street_address=street_address,
            city=city,
            state_or_province=state_or_province,
            zip=zip,
            country=country,
            mock=mock,
            request_options=request_options,
        )
        return _response.data

    def delete(self, brand_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> DeleteBrandsResponse:
        """
        Deletes a 10DLC Brand. Brands with active campaigns cannot be deleted.

        Parameters
        ----------
        brand_id : str
            The unique ID of the 10DLC Brand.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeleteBrandsResponse
            Returns a success confirmation. The 10DLC Brand is deleted.

        Examples
        --------
        from wavix import Wavix

        client = Wavix(
            token="YOUR_TOKEN",
        )
        client.ten_dlc.brands.delete(
            brand_id="BM20QP9",
        )
        """
        _response = self._raw_client.delete(brand_id, request_options=request_options)
        return _response.data

    def qualify_usecase(
        self,
        brand_id: str,
        use_case: QualifyUsecaseBrandsRequestUseCase,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> QualifyUsecaseBrandsResponse:
        """
        Returns the qualification results for a 10DLC Brand use case. Includes MNO-specific attributes, restrictions, and fees.

        Parameters
        ----------
        brand_id : str
            The unique ID of the 10DLC Brand.

        use_case : QualifyUsecaseBrandsRequestUseCase
            Name of the use case to qualify the Brand for.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        QualifyUsecaseBrandsResponse
            Returns the use case qualification results for the Brand.

        Examples
        --------
        from wavix import Wavix

        client = Wavix(
            token="YOUR_TOKEN",
        )
        client.ten_dlc.brands.qualify_usecase(
            brand_id="BMQFB7X",
            use_case="AGENTS_FRANCHISES",
        )
        """
        _response = self._raw_client.qualify_usecase(brand_id, use_case, request_options=request_options)
        return _response.data


class AsyncBrandsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawBrandsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawBrandsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawBrandsClient
        """
        return self._raw_client

    async def list(
        self,
        *,
        dba_name: typing.Optional[str] = None,
        company_name: typing.Optional[str] = None,
        entity_type: typing.Optional[str] = None,
        status: typing.Optional[str] = None,
        country: typing.Optional[str] = None,
        show_deleted: typing.Optional[bool] = None,
        ein_taxid: typing.Optional[str] = None,
        mock: typing.Optional[bool] = None,
        created_before: typing.Optional[str] = None,
        created_after: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        per_page: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListBrandsResponse:
        """
        Returns a paginated list of 10DLC Brands for the authenticated account, filtered by date, name, legal name, and status.

        Parameters
        ----------
        dba_name : typing.Optional[str]
            Filters Brands by `dba_name` (doing-business-as name). Matches partial values.

        company_name : typing.Optional[str]
            Filters Brands by `company_name` (registered legal name). Matches partial values.

        entity_type : typing.Optional[str]
            Filters Brands by business entity type, such as `PRIVATE_PROFIT`.

        status : typing.Optional[str]
            Filters Brands by identity verification status, such as `VERIFIED`.

        country : typing.Optional[str]
            Filters Brands by registration country, as an ISO 3166-1 alpha-2 code (e.g., `US`).

        show_deleted : typing.Optional[bool]
            When `true`, includes deleted Brands in the results. Default `false`.

        ein_taxid : typing.Optional[str]
            Filters Brands by their Employer Identification Number (EIN) or tax ID.

        mock : typing.Optional[bool]
            When `true`, returns only mock Brands used for testing. Default `false`.

        created_before : typing.Optional[str]
            Returns brands created on or before this date, in `YYYY-MM-DD` format.

        created_after : typing.Optional[str]
            Returns brands created on or after this date, in `YYYY-MM-DD` format.

        page : typing.Optional[int]
            Page number to retrieve. Default `1`.

        per_page : typing.Optional[int]
            Number of records to return per page. Default `25`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListBrandsResponse
            Returns a paginated list of 10DLC Brands.

        Examples
        --------
        import asyncio

        from wavix import AsyncWavix

        client = AsyncWavix(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.ten_dlc.brands.list(
                dba_name="Brand",
                company_name="Company",
                entity_type="PRIVATE_PROFIT",
                status="VERIFIED",
                country="US",
                show_deleted=False,
                ein_taxid="999999999",
                mock=False,
                created_before="2024-08-22",
                created_after="2024-08-22",
                page=1,
                per_page=25,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list(
            dba_name=dba_name,
            company_name=company_name,
            entity_type=entity_type,
            status=status,
            country=country,
            show_deleted=show_deleted,
            ein_taxid=ein_taxid,
            mock=mock,
            created_before=created_before,
            created_after=created_after,
            page=page,
            per_page=per_page,
            request_options=request_options,
        )
        return _response.data

    async def create(
        self, *, request: TenDlcBrandCreateRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> CreateBrandsResponse:
        """
        Registers a 10DLC Brand. TCR automatically verifies the brand identity. Only brands with `VERIFIED` or `VETTED_VERIFIED` identity status can register 10DLC Campaigns.

        Parameters
        ----------
        request : TenDlcBrandCreateRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateBrandsResponse
            Returns the registered 10DLC Brand.

        Examples
        --------
        import asyncio

        from wavix import AsyncWavix, TenDlcBrandCreateRequestZero

        client = AsyncWavix(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.ten_dlc.brands.create(
                request=TenDlcBrandCreateRequestZero(),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(request=request, request_options=request_options)
        return _response.data

    async def get(self, brand_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> GetBrandsResponse:
        """
        Returns the 10DLC Brand identified by `brand_id`.

        Parameters
        ----------
        brand_id : str
            The unique ID of the 10DLC Brand.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetBrandsResponse
            Returns the 10DLC Brand.

        Examples
        --------
        import asyncio

        from wavix import AsyncWavix

        client = AsyncWavix(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.ten_dlc.brands.get(
                brand_id="BM20QP9",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(brand_id, request_options=request_options)
        return _response.data

    async def update(
        self,
        brand_id: str,
        *,
        dba_name: typing.Optional[str] = OMIT,
        company_name: typing.Optional[str] = OMIT,
        entity_type: typing.Optional[TenDlcBrandUpdateRequestEntityType] = OMIT,
        vertical: typing.Optional[TenDlcBrandUpdateRequestVertical] = OMIT,
        ein_taxid: typing.Optional[str] = OMIT,
        ein_taxid_country: typing.Optional[str] = OMIT,
        website: typing.Optional[str] = OMIT,
        stock_symbol: typing.Optional[str] = OMIT,
        stock_exchange: typing.Optional[str] = OMIT,
        first_name: typing.Optional[str] = OMIT,
        last_name: typing.Optional[str] = OMIT,
        phone_number: typing.Optional[str] = OMIT,
        email: typing.Optional[str] = OMIT,
        street_address: typing.Optional[str] = OMIT,
        city: typing.Optional[str] = OMIT,
        state_or_province: typing.Optional[str] = OMIT,
        zip: typing.Optional[str] = OMIT,
        country: typing.Optional[str] = OMIT,
        mock: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UpdateBrandsResponse:
        """
        Updates the 10DLC Brand identified by `brand_id`. Changing identity fields, including `ein_taxid`, `ein_taxid_country`, and `entity_type`, resets the Brand status to `UNVERIFIED` and triggers automatic re-submission. Brands in `VETTED_VERIFIED` status or with active Campaigns cannot be updated.

        Parameters
        ----------
        brand_id : str
            The unique ID of the 10DLC Brand.

        dba_name : typing.Optional[str]
            Brand name or DBA

        company_name : typing.Optional[str]
            Legal name of the company

        entity_type : typing.Optional[TenDlcBrandUpdateRequestEntityType]
            Legal entity type of the company. One of `PRIVATE_PROFIT` (privately held for-profit company), `PUBLIC_PROFIT` (publicly traded for-profit company), `NON_PROFIT` (non-profit organization), or `GOVERNMENT` (government entity).

        vertical : typing.Optional[TenDlcBrandUpdateRequestVertical]
            Business segment the Brand operates in. One of:

            - `HEALTHCARE` — healthcare.
            - `PROFESSIONAL` — professional services.
            - `RETAIL` — retail.
            - `TECHNOLOGY` — technology.
            - `EDUCATION` — education.
            - `FINANCIAL` — financial services.
            - `NON_PROFIT` — non-profit organizations.
            - `GOVERNMENT` — government entities.
            - `OTHER` — any segment not listed above.

        ein_taxid : typing.Optional[str]
            IRS Employee Identification Number (EIN) for US-based or foreign companies with EIN. The numeric portion of Tax ID for companies incorporated in other countries.

        ein_taxid_country : typing.Optional[str]
            2-letter ISO country code of the Tax ID issuing country

        website : typing.Optional[str]
            The website of the business

        stock_symbol : typing.Optional[str]
            The stock symbol of the Brand. For PUBLIC_PROFIT Brands only.

        stock_exchange : typing.Optional[str]
            The stock exchange code. For PUBLIC_PROFIT Brands only.

        first_name : typing.Optional[str]
            The first name of the business contact

        last_name : typing.Optional[str]
            The last name of the business contact

        phone_number : typing.Optional[str]
            The support contact telephone in E.164 format

        email : typing.Optional[str]
            The email address of the support contact

        street_address : typing.Optional[str]
            Street name and house number

        city : typing.Optional[str]
            The city name

        state_or_province : typing.Optional[str]
            State or province. For the United States, use 2 character codes.

        zip : typing.Optional[str]
            The business zip or postal code

        country : typing.Optional[str]
            2-letter ISO country code the business address

        mock : typing.Optional[bool]
            Mock flag for testing (optional, defaults to false)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdateBrandsResponse
            Returns the updated 10DLC Brand.

        Examples
        --------
        import asyncio

        from wavix import AsyncWavix

        client = AsyncWavix(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.ten_dlc.brands.update(
                brand_id="BM20QP9",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update(
            brand_id,
            dba_name=dba_name,
            company_name=company_name,
            entity_type=entity_type,
            vertical=vertical,
            ein_taxid=ein_taxid,
            ein_taxid_country=ein_taxid_country,
            website=website,
            stock_symbol=stock_symbol,
            stock_exchange=stock_exchange,
            first_name=first_name,
            last_name=last_name,
            phone_number=phone_number,
            email=email,
            street_address=street_address,
            city=city,
            state_or_province=state_or_province,
            zip=zip,
            country=country,
            mock=mock,
            request_options=request_options,
        )
        return _response.data

    async def delete(
        self, brand_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> DeleteBrandsResponse:
        """
        Deletes a 10DLC Brand. Brands with active campaigns cannot be deleted.

        Parameters
        ----------
        brand_id : str
            The unique ID of the 10DLC Brand.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeleteBrandsResponse
            Returns a success confirmation. The 10DLC Brand is deleted.

        Examples
        --------
        import asyncio

        from wavix import AsyncWavix

        client = AsyncWavix(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.ten_dlc.brands.delete(
                brand_id="BM20QP9",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(brand_id, request_options=request_options)
        return _response.data

    async def qualify_usecase(
        self,
        brand_id: str,
        use_case: QualifyUsecaseBrandsRequestUseCase,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> QualifyUsecaseBrandsResponse:
        """
        Returns the qualification results for a 10DLC Brand use case. Includes MNO-specific attributes, restrictions, and fees.

        Parameters
        ----------
        brand_id : str
            The unique ID of the 10DLC Brand.

        use_case : QualifyUsecaseBrandsRequestUseCase
            Name of the use case to qualify the Brand for.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        QualifyUsecaseBrandsResponse
            Returns the use case qualification results for the Brand.

        Examples
        --------
        import asyncio

        from wavix import AsyncWavix

        client = AsyncWavix(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.ten_dlc.brands.qualify_usecase(
                brand_id="BMQFB7X",
                use_case="AGENTS_FRANCHISES",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.qualify_usecase(brand_id, use_case, request_options=request_options)
        return _response.data
