# This file was auto-generated by Fern from our API Definition.

import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from ...types.success_response import SuccessResponse
from .raw_client import AsyncRawAudioClient, RawAudioClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class AudioClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawAudioClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawAudioClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawAudioClient
        """
        return self._raw_client

    def play(
        self, id: str, *, audio_file: str, request_options: typing.Optional[RequestOptions] = None
    ) -> SuccessResponse:
        """
        Plays an audio prompt into the active call identified by `id`. The audio is audible to the remote party in real time.

        Parameters
        ----------
        id : str
            The `uuid` of the call.

        audio_file : str
            URL of the audio file to play to the call.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SuccessResponse
            Returns a success confirmation. Audio playback starts.

        Examples
        --------
        from wavix import Wavix

        client = Wavix(
            token="YOUR_TOKEN",
        )
        client.call_control.audio.play(
            id="id",
            audio_file="https://examples.com/audio.wav",
        )
        """
        _response = self._raw_client.play(id, audio_file=audio_file, request_options=request_options)
        return _response.data

    def stop(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> SuccessResponse:
        """
        Stops audio playback in the active call identified by `id`.

        Parameters
        ----------
        id : str
            The `uuid` of the call.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SuccessResponse
            Returns a success confirmation. Audio playback stops.

        Examples
        --------
        from wavix import Wavix

        client = Wavix(
            token="YOUR_TOKEN",
        )
        client.call_control.audio.stop(
            id="id",
        )
        """
        _response = self._raw_client.stop(id, request_options=request_options)
        return _response.data


class AsyncAudioClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawAudioClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawAudioClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawAudioClient
        """
        return self._raw_client

    async def play(
        self, id: str, *, audio_file: str, request_options: typing.Optional[RequestOptions] = None
    ) -> SuccessResponse:
        """
        Plays an audio prompt into the active call identified by `id`. The audio is audible to the remote party in real time.

        Parameters
        ----------
        id : str
            The `uuid` of the call.

        audio_file : str
            URL of the audio file to play to the call.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SuccessResponse
            Returns a success confirmation. Audio playback starts.

        Examples
        --------
        import asyncio

        from wavix import AsyncWavix

        client = AsyncWavix(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.call_control.audio.play(
                id="id",
                audio_file="https://examples.com/audio.wav",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.play(id, audio_file=audio_file, request_options=request_options)
        return _response.data

    async def stop(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> SuccessResponse:
        """
        Stops audio playback in the active call identified by `id`.

        Parameters
        ----------
        id : str
            The `uuid` of the call.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SuccessResponse
            Returns a success confirmation. Audio playback stops.

        Examples
        --------
        import asyncio

        from wavix import AsyncWavix

        client = AsyncWavix(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.call_control.audio.stop(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.stop(id, request_options=request_options)
        return _response.data
