# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from ...types.short_link_metrics_response import ShortLinkMetricsResponse
from .raw_client import AsyncRawMetricsClient, RawMetricsClient


class MetricsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawMetricsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawMetricsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawMetricsClient
        """
        return self._raw_client

    def list(
        self,
        *,
        from_: dt.date,
        to: dt.date,
        phone: typing.Optional[str] = None,
        utm_campaign: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        per_page: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ShortLinkMetricsResponse:
        """
        Returns per-click metrics for short links, including device, location, and campaign attribution, within the requested date range.

        Parameters
        ----------
        from_ : dt.date
            Start of the date range to query, in `YYYY-MM-DD` format. Inclusive.

        to : dt.date
            End of the date range to query, in `YYYY-MM-DD` format. Inclusive.

        phone : typing.Optional[str]
            Filters metrics by the phone number associated with the click, in E.164 format.

        utm_campaign : typing.Optional[str]
            Filters metrics by `utm_campaign` name.

        page : typing.Optional[int]
            Page number to retrieve. Default `1`.

        per_page : typing.Optional[int]
            Number of records to return per page. Default `25`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ShortLinkMetricsResponse
            Returns a paginated list of short link metrics.

        Examples
        --------
        import datetime

        from wavix import Wavix

        client = Wavix(
            token="YOUR_TOKEN",
        )
        client.link_shortener.metrics.list(
            from_=datetime.date.fromisoformat(
                "2023-05-01",
            ),
            to=datetime.date.fromisoformat(
                "2023-05-31",
            ),
            phone="1872025555",
            utm_campaign="summer",
            page=1,
            per_page=25,
        )
        """
        _response = self._raw_client.list(
            from_=from_,
            to=to,
            phone=phone,
            utm_campaign=utm_campaign,
            page=page,
            per_page=per_page,
            request_options=request_options,
        )
        return _response.data


class AsyncMetricsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawMetricsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawMetricsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawMetricsClient
        """
        return self._raw_client

    async def list(
        self,
        *,
        from_: dt.date,
        to: dt.date,
        phone: typing.Optional[str] = None,
        utm_campaign: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        per_page: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ShortLinkMetricsResponse:
        """
        Returns per-click metrics for short links, including device, location, and campaign attribution, within the requested date range.

        Parameters
        ----------
        from_ : dt.date
            Start of the date range to query, in `YYYY-MM-DD` format. Inclusive.

        to : dt.date
            End of the date range to query, in `YYYY-MM-DD` format. Inclusive.

        phone : typing.Optional[str]
            Filters metrics by the phone number associated with the click, in E.164 format.

        utm_campaign : typing.Optional[str]
            Filters metrics by `utm_campaign` name.

        page : typing.Optional[int]
            Page number to retrieve. Default `1`.

        per_page : typing.Optional[int]
            Number of records to return per page. Default `25`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ShortLinkMetricsResponse
            Returns a paginated list of short link metrics.

        Examples
        --------
        import asyncio
        import datetime

        from wavix import AsyncWavix

        client = AsyncWavix(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.link_shortener.metrics.list(
                from_=datetime.date.fromisoformat(
                    "2023-05-01",
                ),
                to=datetime.date.fromisoformat(
                    "2023-05-31",
                ),
                phone="1872025555",
                utm_campaign="summer",
                page=1,
                per_page=25,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list(
            from_=from_,
            to=to,
            phone=phone,
            utm_campaign=utm_campaign,
            page=page,
            per_page=per_page,
            request_options=request_options,
        )
        return _response.data
