# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ....types.financial_transaction import FinancialTransaction
from ....types.pagination import Pagination


class ListTransactionsResponse(UniversalBaseModel):
    is_empty: bool = pydantic.Field()
    """
    Indicates whether there are no transactions.
    """

    transactions: typing.List[FinancialTransaction] = pydantic.Field()
    """
    List of transactions.
    """

    pagination: Pagination

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
