# This file was auto-generated by Fern from our API Definition.

import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from .raw_client import AsyncRawCountriesClient, RawCountriesClient
from .types.list_countries_response import ListCountriesResponse


class CountriesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawCountriesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawCountriesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawCountriesClient
        """
        return self._raw_client

    def list(
        self,
        *,
        text_enabled_only: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListCountriesResponse:
        """
        Returns a list of countries where phone numbers are available.

        Parameters
        ----------
        text_enabled_only : typing.Optional[bool]
            When `true`, returns only countries that offer text-enabled phone numbers.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListCountriesResponse
            Returns the list of countries with available phone numbers.

        Examples
        --------
        from wavix import Wavix

        client = Wavix(
            token="YOUR_TOKEN",
        )
        client.buy.countries.list()
        """
        _response = self._raw_client.list(text_enabled_only=text_enabled_only, request_options=request_options)
        return _response.data


class AsyncCountriesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawCountriesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawCountriesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawCountriesClient
        """
        return self._raw_client

    async def list(
        self,
        *,
        text_enabled_only: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListCountriesResponse:
        """
        Returns a list of countries where phone numbers are available.

        Parameters
        ----------
        text_enabled_only : typing.Optional[bool]
            When `true`, returns only countries that offer text-enabled phone numbers.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListCountriesResponse
            Returns the list of countries with available phone numbers.

        Examples
        --------
        import asyncio

        from wavix import AsyncWavix

        client = AsyncWavix(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.buy.countries.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(text_enabled_only=text_enabled_only, request_options=request_options)
        return _response.data
