# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import encode_path_param
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..errors.bad_request_error import BadRequestError
from ..errors.not_found_error import NotFoundError
from ..errors.unauthorized_error import UnauthorizedError
from ..types.call_create_response import CallCreateResponse
from ..types.call_list_response import CallListResponse
from ..types.call_response import CallResponse
from ..types.call_stream_channel import CallStreamChannel
from ..types.call_stream_type import CallStreamType
from ..types.success_response import SuccessResponse
from ..types.unauthorized_error_response import UnauthorizedErrorResponse
from .types.call_dtmf_collect_request_prompt import CallDtmfCollectRequestPrompt
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawCallControlClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list(self, *, request_options: typing.Optional[RequestOptions] = None) -> HttpResponse[CallListResponse]:
        """
        Returns the calls currently in progress for the authenticated account.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[CallListResponse]
            Returns the list of active calls.
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/calls",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CallListResponse,
                    parse_obj_as(
                        type_=CallListResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        UnauthorizedErrorResponse,
                        parse_obj_as(
                            type_=UnauthorizedErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def create(
        self,
        *,
        from_: str,
        to: str,
        callback_url: str,
        recording: typing.Optional[bool] = OMIT,
        voicemail_detection: typing.Optional[bool] = OMIT,
        tag: typing.Optional[str] = OMIT,
        timeout: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[CallCreateResponse]:
        """
        Places an outbound call. Returns the call with its `uuid` for tracking and control.

        Parameters
        ----------
        from_ : str
            Caller ID. Must be an active or verified phone number on the account.

        to : str
            Destination number in E.164 format

        callback_url : str
            The callback URL where Wavix sends the call status updates

        recording : typing.Optional[bool]
            Specifies whether to record the call

        voicemail_detection : typing.Optional[bool]
            Specifies whether the AMD is turned on for the call

        tag : typing.Optional[str]
            Call metadata

        timeout : typing.Optional[int]
            The ring timeout, in seconds, before the call is considered unanswered.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[CallCreateResponse]
            Returns the created call.
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/calls",
            method="POST",
            json={
                "from": from_,
                "to": to,
                "callback_url": callback_url,
                "recording": recording,
                "voicemail_detection": voicemail_detection,
                "tag": tag,
                "timeout": timeout,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CallCreateResponse,
                    parse_obj_as(
                        type_=CallCreateResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        UnauthorizedErrorResponse,
                        parse_obj_as(
                            type_=UnauthorizedErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> HttpResponse[CallResponse]:
        """
        Returns the call identified by `id`, including its current event and timestamps.

        Parameters
        ----------
        id : str
            The `uuid` of the call.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[CallResponse]
            Returns the call.
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/calls/{encode_path_param(id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CallResponse,
                    parse_obj_as(
                        type_=CallResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        UnauthorizedErrorResponse,
                        parse_obj_as(
                            type_=UnauthorizedErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def delete(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[SuccessResponse]:
        """
        Ends the active call identified by `id` by hanging up.

        Parameters
        ----------
        id : str
            The `uuid` of the call.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[SuccessResponse]
            Returns a success confirmation. The call is ended.
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/calls/{encode_path_param(id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SuccessResponse,
                    parse_obj_as(
                        type_=SuccessResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        UnauthorizedErrorResponse,
                        parse_obj_as(
                            type_=UnauthorizedErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def update(
        self, id: str, *, tag: str, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[SuccessResponse]:
        """
        Updates the active call identified by `id`. Only the `tag` field can be changed.

        Parameters
        ----------
        id : str
            The `uuid` of the call.

        tag : str
            User-defined label attached to the Call for tracking or reporting.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[SuccessResponse]
            Returns a success confirmation. The call `tag` is updated.
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/calls/{encode_path_param(id)}",
            method="PATCH",
            json={
                "tag": tag,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SuccessResponse,
                    parse_obj_as(
                        type_=SuccessResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        UnauthorizedErrorResponse,
                        parse_obj_as(
                            type_=UnauthorizedErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def answer(
        self,
        id: str,
        *,
        call_recording: typing.Optional[bool] = OMIT,
        call_transcription: typing.Optional[bool] = OMIT,
        stream_url: typing.Optional[str] = OMIT,
        stream_type: typing.Optional[CallStreamType] = OMIT,
        stream_channel: typing.Optional[CallStreamChannel] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[SuccessResponse]:
        """
        Answers the inbound call identified by `id`. Optionally starts media streaming on answer.

        Parameters
        ----------
        id : str
            The `uuid` of the call.

        call_recording : typing.Optional[bool]
            Indicates whether the call should be recorded.

        call_transcription : typing.Optional[bool]
            Indicates whether the call should be transcribed after it ends.

        stream_url : typing.Optional[str]
            WebSocket URL to stream the call.

        stream_type : typing.Optional[CallStreamType]
            Direction of audio streamed to `stream_url`.

        stream_channel : typing.Optional[CallStreamChannel]
            Audio channel streamed to `stream_url`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[SuccessResponse]
            Returns a success confirmation. The call is answered.
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/calls/{encode_path_param(id)}/answer",
            method="POST",
            json={
                "call_recording": call_recording,
                "call_transcription": call_transcription,
                "stream_url": stream_url,
                "stream_type": stream_type,
                "stream_channel": stream_channel,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SuccessResponse,
                    parse_obj_as(
                        type_=SuccessResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        UnauthorizedErrorResponse,
                        parse_obj_as(
                            type_=UnauthorizedErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def collect(
        self,
        id: str,
        *,
        max_digits: typing.Optional[int] = OMIT,
        timeout: typing.Optional[int] = OMIT,
        termination_character: typing.Optional[str] = OMIT,
        max_attempts: typing.Optional[int] = OMIT,
        prompt: typing.Optional[CallDtmfCollectRequestPrompt] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[SuccessResponse]:
        """
        Collects DTMF keypad input from the caller on the active call identified by `id`.

        Parameters
        ----------
        id : str
            The `uuid` of the call.

        max_digits : typing.Optional[int]
            Maximum number of digits to collect.

        timeout : typing.Optional[int]
            Timeout for digit collection in seconds.

        termination_character : typing.Optional[str]
            DTMF character that ends input collection.

        max_attempts : typing.Optional[int]
            Maximum number of attempts.

        prompt : typing.Optional[CallDtmfCollectRequestPrompt]
            Prompt to play before collecting digits.
             Play a prerecorded audio file or use Wavix Text-To-Speech.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[SuccessResponse]
            Returns a success confirmation. DTMF collection starts.
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/calls/{encode_path_param(id)}/collect",
            method="POST",
            json={
                "max_digits": max_digits,
                "timeout": timeout,
                "termination_character": termination_character,
                "max_attempts": max_attempts,
                "prompt": convert_and_respect_annotation_metadata(
                    object_=prompt, annotation=CallDtmfCollectRequestPrompt, direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SuccessResponse,
                    parse_obj_as(
                        type_=SuccessResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        UnauthorizedErrorResponse,
                        parse_obj_as(
                            type_=UnauthorizedErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawCallControlClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[CallListResponse]:
        """
        Returns the calls currently in progress for the authenticated account.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[CallListResponse]
            Returns the list of active calls.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/calls",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CallListResponse,
                    parse_obj_as(
                        type_=CallListResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        UnauthorizedErrorResponse,
                        parse_obj_as(
                            type_=UnauthorizedErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def create(
        self,
        *,
        from_: str,
        to: str,
        callback_url: str,
        recording: typing.Optional[bool] = OMIT,
        voicemail_detection: typing.Optional[bool] = OMIT,
        tag: typing.Optional[str] = OMIT,
        timeout: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[CallCreateResponse]:
        """
        Places an outbound call. Returns the call with its `uuid` for tracking and control.

        Parameters
        ----------
        from_ : str
            Caller ID. Must be an active or verified phone number on the account.

        to : str
            Destination number in E.164 format

        callback_url : str
            The callback URL where Wavix sends the call status updates

        recording : typing.Optional[bool]
            Specifies whether to record the call

        voicemail_detection : typing.Optional[bool]
            Specifies whether the AMD is turned on for the call

        tag : typing.Optional[str]
            Call metadata

        timeout : typing.Optional[int]
            The ring timeout, in seconds, before the call is considered unanswered.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[CallCreateResponse]
            Returns the created call.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/calls",
            method="POST",
            json={
                "from": from_,
                "to": to,
                "callback_url": callback_url,
                "recording": recording,
                "voicemail_detection": voicemail_detection,
                "tag": tag,
                "timeout": timeout,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CallCreateResponse,
                    parse_obj_as(
                        type_=CallCreateResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        UnauthorizedErrorResponse,
                        parse_obj_as(
                            type_=UnauthorizedErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[CallResponse]:
        """
        Returns the call identified by `id`, including its current event and timestamps.

        Parameters
        ----------
        id : str
            The `uuid` of the call.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[CallResponse]
            Returns the call.
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/calls/{encode_path_param(id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CallResponse,
                    parse_obj_as(
                        type_=CallResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        UnauthorizedErrorResponse,
                        parse_obj_as(
                            type_=UnauthorizedErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def delete(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[SuccessResponse]:
        """
        Ends the active call identified by `id` by hanging up.

        Parameters
        ----------
        id : str
            The `uuid` of the call.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[SuccessResponse]
            Returns a success confirmation. The call is ended.
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/calls/{encode_path_param(id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SuccessResponse,
                    parse_obj_as(
                        type_=SuccessResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        UnauthorizedErrorResponse,
                        parse_obj_as(
                            type_=UnauthorizedErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def update(
        self, id: str, *, tag: str, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[SuccessResponse]:
        """
        Updates the active call identified by `id`. Only the `tag` field can be changed.

        Parameters
        ----------
        id : str
            The `uuid` of the call.

        tag : str
            User-defined label attached to the Call for tracking or reporting.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[SuccessResponse]
            Returns a success confirmation. The call `tag` is updated.
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/calls/{encode_path_param(id)}",
            method="PATCH",
            json={
                "tag": tag,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SuccessResponse,
                    parse_obj_as(
                        type_=SuccessResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        UnauthorizedErrorResponse,
                        parse_obj_as(
                            type_=UnauthorizedErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def answer(
        self,
        id: str,
        *,
        call_recording: typing.Optional[bool] = OMIT,
        call_transcription: typing.Optional[bool] = OMIT,
        stream_url: typing.Optional[str] = OMIT,
        stream_type: typing.Optional[CallStreamType] = OMIT,
        stream_channel: typing.Optional[CallStreamChannel] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[SuccessResponse]:
        """
        Answers the inbound call identified by `id`. Optionally starts media streaming on answer.

        Parameters
        ----------
        id : str
            The `uuid` of the call.

        call_recording : typing.Optional[bool]
            Indicates whether the call should be recorded.

        call_transcription : typing.Optional[bool]
            Indicates whether the call should be transcribed after it ends.

        stream_url : typing.Optional[str]
            WebSocket URL to stream the call.

        stream_type : typing.Optional[CallStreamType]
            Direction of audio streamed to `stream_url`.

        stream_channel : typing.Optional[CallStreamChannel]
            Audio channel streamed to `stream_url`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[SuccessResponse]
            Returns a success confirmation. The call is answered.
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/calls/{encode_path_param(id)}/answer",
            method="POST",
            json={
                "call_recording": call_recording,
                "call_transcription": call_transcription,
                "stream_url": stream_url,
                "stream_type": stream_type,
                "stream_channel": stream_channel,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SuccessResponse,
                    parse_obj_as(
                        type_=SuccessResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        UnauthorizedErrorResponse,
                        parse_obj_as(
                            type_=UnauthorizedErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def collect(
        self,
        id: str,
        *,
        max_digits: typing.Optional[int] = OMIT,
        timeout: typing.Optional[int] = OMIT,
        termination_character: typing.Optional[str] = OMIT,
        max_attempts: typing.Optional[int] = OMIT,
        prompt: typing.Optional[CallDtmfCollectRequestPrompt] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[SuccessResponse]:
        """
        Collects DTMF keypad input from the caller on the active call identified by `id`.

        Parameters
        ----------
        id : str
            The `uuid` of the call.

        max_digits : typing.Optional[int]
            Maximum number of digits to collect.

        timeout : typing.Optional[int]
            Timeout for digit collection in seconds.

        termination_character : typing.Optional[str]
            DTMF character that ends input collection.

        max_attempts : typing.Optional[int]
            Maximum number of attempts.

        prompt : typing.Optional[CallDtmfCollectRequestPrompt]
            Prompt to play before collecting digits.
             Play a prerecorded audio file or use Wavix Text-To-Speech.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[SuccessResponse]
            Returns a success confirmation. DTMF collection starts.
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/calls/{encode_path_param(id)}/collect",
            method="POST",
            json={
                "max_digits": max_digits,
                "timeout": timeout,
                "termination_character": termination_character,
                "max_attempts": max_attempts,
                "prompt": convert_and_respect_annotation_metadata(
                    object_=prompt, annotation=CallDtmfCollectRequestPrompt, direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SuccessResponse,
                    parse_obj_as(
                        type_=SuccessResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        UnauthorizedErrorResponse,
                        parse_obj_as(
                            type_=UnauthorizedErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
