# This file was auto-generated by Fern from our API Definition.

import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from ...types.success_response import SuccessResponse
from ...types.web_rtc_token import WebRtcToken
from ...types.web_rtc_token_response import WebRtcTokenResponse
from ...types.web_rtc_tokens_list_response import WebRtcTokensListResponse
from .raw_client import AsyncRawTokensClient, RawTokensClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class TokensClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawTokensClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawTokensClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawTokensClient
        """
        return self._raw_client

    def list(self, *, request_options: typing.Optional[RequestOptions] = None) -> WebRtcTokensListResponse:
        """
        Returns a paginated list of active Wavix Embeddable widget tokens for the authenticated account.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WebRtcTokensListResponse
            Returns a paginated list of active widget tokens.

        Examples
        --------
        from wavix import Wavix

        client = Wavix(
            token="YOUR_TOKEN",
        )
        client.webrtc.tokens.list()
        """
        _response = self._raw_client.list(request_options=request_options)
        return _response.data

    def create(
        self,
        *,
        sip_trunk: str,
        payload: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        ttl: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> WebRtcTokenResponse:
        """
        Creates a Wavix Embeddable widget token that authenticates a browser-based softphone session. The token expires after `ttl` seconds.

        Parameters
        ----------
        sip_trunk : str
            Name of the SIP trunk the token authenticates against.

        payload : typing.Optional[typing.Dict[str, typing.Any]]
            Arbitrary client-defined data to associate with the token.

        ttl : typing.Optional[int]
            Time to live in seconds. Pass `null` for no expiration.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WebRtcTokenResponse
            Returns the created widget token.

        Examples
        --------
        from wavix import Wavix

        client = Wavix(
            token="YOUR_TOKEN",
        )
        client.webrtc.tokens.create(
            sip_trunk="my-sip-trunk",
            payload={"user_id": "42"},
            ttl=3600,
        )
        """
        _response = self._raw_client.create(
            sip_trunk=sip_trunk, payload=payload, ttl=ttl, request_options=request_options
        )
        return _response.data

    def get(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> WebRtcToken:
        """
        Returns the Wavix Embeddable widget token identified by `id`.

        Parameters
        ----------
        id : str
            The UUID of the widget token to retrieve.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WebRtcToken
            Returns the widget token.

        Examples
        --------
        from wavix import Wavix

        client = Wavix(
            token="YOUR_TOKEN",
        )
        client.webrtc.tokens.get(
            id="id",
        )
        """
        _response = self._raw_client.get(id, request_options=request_options)
        return _response.data

    def update(
        self, id: str, *, payload: typing.Dict[str, typing.Any], request_options: typing.Optional[RequestOptions] = None
    ) -> WebRtcToken:
        """
        Updates the `payload` carried by the Wavix Embeddable widget token identified by `id`.

        Parameters
        ----------
        id : str
            The UUID of the widget token to update.

        payload : typing.Dict[str, typing.Any]
            Arbitrary client-defined data to associate with the token, replacing the existing payload.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WebRtcToken
            Returns the updated widget token.

        Examples
        --------
        from wavix import Wavix

        client = Wavix(
            token="YOUR_TOKEN",
        )
        client.webrtc.tokens.update(
            id="id",
            payload={"key": "value"},
        )
        """
        _response = self._raw_client.update(id, payload=payload, request_options=request_options)
        return _response.data

    def delete(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> SuccessResponse:
        """
        Deletes the Wavix Embeddable widget token identified by `id`. The token can no longer authenticate widget sessions, and any active session using it ends.

        Parameters
        ----------
        id : str
            The UUID of the widget token to delete.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SuccessResponse
            Returns a success confirmation. The widget token is deleted.

        Examples
        --------
        from wavix import Wavix

        client = Wavix(
            token="YOUR_TOKEN",
        )
        client.webrtc.tokens.delete(
            id="id",
        )
        """
        _response = self._raw_client.delete(id, request_options=request_options)
        return _response.data


class AsyncTokensClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawTokensClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawTokensClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawTokensClient
        """
        return self._raw_client

    async def list(self, *, request_options: typing.Optional[RequestOptions] = None) -> WebRtcTokensListResponse:
        """
        Returns a paginated list of active Wavix Embeddable widget tokens for the authenticated account.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WebRtcTokensListResponse
            Returns a paginated list of active widget tokens.

        Examples
        --------
        import asyncio

        from wavix import AsyncWavix

        client = AsyncWavix(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.webrtc.tokens.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(request_options=request_options)
        return _response.data

    async def create(
        self,
        *,
        sip_trunk: str,
        payload: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        ttl: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> WebRtcTokenResponse:
        """
        Creates a Wavix Embeddable widget token that authenticates a browser-based softphone session. The token expires after `ttl` seconds.

        Parameters
        ----------
        sip_trunk : str
            Name of the SIP trunk the token authenticates against.

        payload : typing.Optional[typing.Dict[str, typing.Any]]
            Arbitrary client-defined data to associate with the token.

        ttl : typing.Optional[int]
            Time to live in seconds. Pass `null` for no expiration.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WebRtcTokenResponse
            Returns the created widget token.

        Examples
        --------
        import asyncio

        from wavix import AsyncWavix

        client = AsyncWavix(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.webrtc.tokens.create(
                sip_trunk="my-sip-trunk",
                payload={"user_id": "42"},
                ttl=3600,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(
            sip_trunk=sip_trunk, payload=payload, ttl=ttl, request_options=request_options
        )
        return _response.data

    async def get(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> WebRtcToken:
        """
        Returns the Wavix Embeddable widget token identified by `id`.

        Parameters
        ----------
        id : str
            The UUID of the widget token to retrieve.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WebRtcToken
            Returns the widget token.

        Examples
        --------
        import asyncio

        from wavix import AsyncWavix

        client = AsyncWavix(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.webrtc.tokens.get(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(id, request_options=request_options)
        return _response.data

    async def update(
        self, id: str, *, payload: typing.Dict[str, typing.Any], request_options: typing.Optional[RequestOptions] = None
    ) -> WebRtcToken:
        """
        Updates the `payload` carried by the Wavix Embeddable widget token identified by `id`.

        Parameters
        ----------
        id : str
            The UUID of the widget token to update.

        payload : typing.Dict[str, typing.Any]
            Arbitrary client-defined data to associate with the token, replacing the existing payload.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WebRtcToken
            Returns the updated widget token.

        Examples
        --------
        import asyncio

        from wavix import AsyncWavix

        client = AsyncWavix(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.webrtc.tokens.update(
                id="id",
                payload={"key": "value"},
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update(id, payload=payload, request_options=request_options)
        return _response.data

    async def delete(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> SuccessResponse:
        """
        Deletes the Wavix Embeddable widget token identified by `id`. The token can no longer authenticate widget sessions, and any active session using it ends.

        Parameters
        ----------
        id : str
            The UUID of the widget token to delete.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SuccessResponse
            Returns a success confirmation. The widget token is deleted.

        Examples
        --------
        import asyncio

        from wavix import AsyncWavix

        client = AsyncWavix(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.webrtc.tokens.delete(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(id, request_options=request_options)
        return _response.data
