# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import encode_path_param
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..errors.bad_request_error import BadRequestError
from ..errors.forbidden_error import ForbiddenError
from ..errors.not_found_error import NotFoundError
from ..errors.unauthorized_error import UnauthorizedError
from ..errors.unprocessable_entity_error import UnprocessableEntityError
from ..types.sip_trunk_create_request_allowed_ips_item import SipTrunkCreateRequestAllowedIpsItem
from ..types.sip_trunk_create_request_host_request import SipTrunkCreateRequestHostRequest
from ..types.sip_trunk_list_response import SipTrunkListResponse
from ..types.sip_trunk_response import SipTrunkResponse
from ..types.success_response import SuccessResponse
from ..types.unauthorized_error_response import UnauthorizedErrorResponse
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawSipTrunksClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list(
        self,
        *,
        page: typing.Optional[int] = None,
        per_page: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[SipTrunkListResponse]:
        """
        Returns a paginated list of SIP trunks for the authenticated account.

        Parameters
        ----------
        page : typing.Optional[int]
            Page number to retrieve. Default `1`.

        per_page : typing.Optional[int]
            Number of records to return per page. Default `25`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[SipTrunkListResponse]
            Returns a paginated list of SIP trunks.
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/trunks",
            method="GET",
            params={
                "page": page,
                "per_page": per_page,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SipTrunkListResponse,
                    parse_obj_as(
                        type_=SipTrunkListResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        UnauthorizedErrorResponse,
                        parse_obj_as(
                            type_=UnauthorizedErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def create(
        self,
        *,
        label: str,
        password: str,
        callerid: str,
        ip_restrict: bool,
        didinfo_enabled: bool,
        call_restrict: bool,
        channels_restrict: bool,
        rewrite_enabled: bool,
        transcription_enabled: bool,
        transcription_threshold: int,
        host_request: typing.Optional[SipTrunkCreateRequestHostRequest] = OMIT,
        multiple_numbers: typing.Optional[bool] = OMIT,
        allowed_ips: typing.Optional[typing.Sequence[SipTrunkCreateRequestAllowedIpsItem]] = OMIT,
        call_limit: typing.Optional[int] = OMIT,
        cost_limit: typing.Optional[bool] = OMIT,
        max_call_cost: typing.Optional[float] = OMIT,
        max_channels: typing.Optional[int] = OMIT,
        rewrite_prefix: typing.Optional[str] = OMIT,
        rewrite_cond: typing.Optional[str] = OMIT,
        call_recording_enabled: typing.Optional[bool] = OMIT,
        machine_detection_enabled: typing.Optional[bool] = OMIT,
        encrypted_media: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[SipTrunkResponse]:
        """
        Creates a SIP trunk for routing inbound and outbound calls. Returns the trunk with its generated `access_token`.

        Parameters
        ----------
        label : str
            User-defined name of the SIP trunk

        password : str
            Password set for the SIP trunk. A strong password helps keep the trunk secure.

        callerid : str
            Caller ID associated with the SIP trunk. Must be an active or verified number on the account.

        ip_restrict : bool
            Indicates whether SIP trunk registration is allowed from only specific public static IP addresses. When set to `true`, the `allowed_ips` parameter must be provided.

        didinfo_enabled : bool
            Indicates whether inbound calls include dialed number information in the `To` header of SIP INVITE requests

        call_restrict : bool
            Indicates whether a maximum call duration limit is enforced for the SIP trunk

        channels_restrict : bool
            Indicates whether a limit on the number of concurrent outbound calls is enforced for the SIP trunk

        rewrite_enabled : bool
            Indicates whether a custom dial plan is activated for the SIP trunk

        transcription_enabled : bool
            Indicates whether automatic call transcription is enabled for the SIP trunk.
            Available for `Flex Pro` customers only.

        transcription_threshold : int
            Transcriptions will be generated for calls that meet or exceed the specified minimal call duration threshold, in seconds.
            Available for `Flex Pro` customers only.

        host_request : typing.Optional[SipTrunkCreateRequestHostRequest]
            For SIP trunks with IP authentication, includes the SIP endpoint public static IP address and the status of the authentication request. Wavix authenticates all SIP traffic originating from this IP address.

        multiple_numbers : typing.Optional[bool]
            Indicates whether any active or verified phone number on the account can be used as the Caller ID for the SIP trunk.

        allowed_ips : typing.Optional[typing.Sequence[SipTrunkCreateRequestAllowedIpsItem]]
            A list of public static IP addresses allowed to register with the SIP trunk

        call_limit : typing.Optional[int]
            Maximum call duration for the SIP trunk, in seconds. Must not exceed the maximum duration set for the account. Ignored when `call_restrict` is `false`.

        cost_limit : typing.Optional[bool]
            Indicates if the max cost limit for an outbound call limit is activated for the SIP trunk.

        max_call_cost : typing.Optional[float]
            Maximum cost for an outbound call, in USD

        max_channels : typing.Optional[int]
            Maximum number of concurrent outbound calls for the SIP trunk. Must not exceed the outbound channel capacity set for the account. Ignored when `channels_restrict` is `false`.

        rewrite_prefix : typing.Optional[str]
            Digits to automatically prepend to each dialed phone number

        rewrite_cond : typing.Optional[str]
            Number of leading digits to automatically remove from each dialed phone number

        call_recording_enabled : typing.Optional[bool]
            Indicates whether outbound call recording is enabled for the SIP trunk

        machine_detection_enabled : typing.Optional[bool]
            Indicates whether automatic voicemail detection is enabled for the SIP trunk.
            Available for `Flex Pro` customers only.

        encrypted_media : typing.Optional[bool]
            Indicates whether SRTP media encryption is enabled for the SIP trunk.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[SipTrunkResponse]
            Returns the created SIP trunk.
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/trunks",
            method="POST",
            json={
                "label": label,
                "password": password,
                "host_request": convert_and_respect_annotation_metadata(
                    object_=host_request, annotation=SipTrunkCreateRequestHostRequest, direction="write"
                ),
                "callerid": callerid,
                "multiple_numbers": multiple_numbers,
                "ip_restrict": ip_restrict,
                "allowed_ips": convert_and_respect_annotation_metadata(
                    object_=allowed_ips,
                    annotation=typing.Optional[typing.Sequence[SipTrunkCreateRequestAllowedIpsItem]],
                    direction="write",
                ),
                "didinfo_enabled": didinfo_enabled,
                "call_restrict": call_restrict,
                "call_limit": call_limit,
                "cost_limit": cost_limit,
                "max_call_cost": max_call_cost,
                "channels_restrict": channels_restrict,
                "max_channels": max_channels,
                "rewrite_enabled": rewrite_enabled,
                "rewrite_prefix": rewrite_prefix,
                "rewrite_cond": rewrite_cond,
                "call_recording_enabled": call_recording_enabled,
                "transcription_enabled": transcription_enabled,
                "transcription_threshold": transcription_threshold,
                "machine_detection_enabled": machine_detection_enabled,
                "encrypted_media": encrypted_media,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SipTrunkResponse,
                    parse_obj_as(
                        type_=SipTrunkResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        UnauthorizedErrorResponse,
                        parse_obj_as(
                            type_=UnauthorizedErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get(
        self, id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[SipTrunkResponse]:
        """
        Returns the SIP trunk identified by `id`.

        Parameters
        ----------
        id : int
            The unique ID of the SIP trunk.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[SipTrunkResponse]
            Returns the SIP trunk.
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/trunks/{encode_path_param(id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SipTrunkResponse,
                    parse_obj_as(
                        type_=SipTrunkResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        UnauthorizedErrorResponse,
                        parse_obj_as(
                            type_=UnauthorizedErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def update(
        self,
        id: int,
        *,
        label: str,
        password: str,
        callerid: str,
        ip_restrict: bool,
        didinfo_enabled: bool,
        call_restrict: bool,
        channels_restrict: bool,
        rewrite_enabled: bool,
        transcription_enabled: bool,
        transcription_threshold: int,
        host_request: typing.Optional[SipTrunkCreateRequestHostRequest] = OMIT,
        multiple_numbers: typing.Optional[bool] = OMIT,
        allowed_ips: typing.Optional[typing.Sequence[SipTrunkCreateRequestAllowedIpsItem]] = OMIT,
        call_limit: typing.Optional[int] = OMIT,
        cost_limit: typing.Optional[bool] = OMIT,
        max_call_cost: typing.Optional[float] = OMIT,
        max_channels: typing.Optional[int] = OMIT,
        rewrite_prefix: typing.Optional[str] = OMIT,
        rewrite_cond: typing.Optional[str] = OMIT,
        call_recording_enabled: typing.Optional[bool] = OMIT,
        machine_detection_enabled: typing.Optional[bool] = OMIT,
        encrypted_media: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[SipTrunkResponse]:
        """
        Replaces the configuration of the SIP trunk identified by `id`. Omitted fields revert to their defaults.

        Parameters
        ----------
        id : int
            The unique ID of the SIP trunk.

        label : str
            User-defined name of the SIP trunk

        password : str
            Password set for the SIP trunk. A strong password helps keep the trunk secure.

        callerid : str
            Caller ID associated with the SIP trunk. Must be an active or verified number on the account.

        ip_restrict : bool
            Indicates whether SIP trunk registration is allowed from only specific public static IP addresses. When set to `true`, the `allowed_ips` parameter must be provided.

        didinfo_enabled : bool
            Indicates whether inbound calls include dialed number information in the `To` header of SIP INVITE requests

        call_restrict : bool
            Indicates whether a maximum call duration limit is enforced for the SIP trunk

        channels_restrict : bool
            Indicates whether a limit on the number of concurrent outbound calls is enforced for the SIP trunk

        rewrite_enabled : bool
            Indicates whether a custom dial plan is activated for the SIP trunk

        transcription_enabled : bool
            Indicates whether automatic call transcription is enabled for the SIP trunk.
            Available for `Flex Pro` customers only.

        transcription_threshold : int
            Transcriptions will be generated for calls that meet or exceed the specified minimal call duration threshold, in seconds.
            Available for `Flex Pro` customers only.

        host_request : typing.Optional[SipTrunkCreateRequestHostRequest]
            For SIP trunks with IP authentication, includes the SIP endpoint public static IP address and the status of the authentication request. Wavix authenticates all SIP traffic originating from this IP address.

        multiple_numbers : typing.Optional[bool]
            Indicates whether any active or verified phone number on the account can be used as the Caller ID for the SIP trunk.

        allowed_ips : typing.Optional[typing.Sequence[SipTrunkCreateRequestAllowedIpsItem]]
            A list of public static IP addresses allowed to register with the SIP trunk

        call_limit : typing.Optional[int]
            Maximum call duration for the SIP trunk, in seconds. Must not exceed the maximum duration set for the account. Ignored when `call_restrict` is `false`.

        cost_limit : typing.Optional[bool]
            Indicates if the max cost limit for an outbound call limit is activated for the SIP trunk.

        max_call_cost : typing.Optional[float]
            Maximum cost for an outbound call, in USD

        max_channels : typing.Optional[int]
            Maximum number of concurrent outbound calls for the SIP trunk. Must not exceed the outbound channel capacity set for the account. Ignored when `channels_restrict` is `false`.

        rewrite_prefix : typing.Optional[str]
            Digits to automatically prepend to each dialed phone number

        rewrite_cond : typing.Optional[str]
            Number of leading digits to automatically remove from each dialed phone number

        call_recording_enabled : typing.Optional[bool]
            Indicates whether outbound call recording is enabled for the SIP trunk

        machine_detection_enabled : typing.Optional[bool]
            Indicates whether automatic voicemail detection is enabled for the SIP trunk.
            Available for `Flex Pro` customers only.

        encrypted_media : typing.Optional[bool]
            Indicates whether SRTP media encryption is enabled for the SIP trunk.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[SipTrunkResponse]
            Returns the updated SIP trunk.
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/trunks/{encode_path_param(id)}",
            method="PUT",
            json={
                "label": label,
                "password": password,
                "host_request": convert_and_respect_annotation_metadata(
                    object_=host_request, annotation=SipTrunkCreateRequestHostRequest, direction="write"
                ),
                "callerid": callerid,
                "multiple_numbers": multiple_numbers,
                "ip_restrict": ip_restrict,
                "allowed_ips": convert_and_respect_annotation_metadata(
                    object_=allowed_ips,
                    annotation=typing.Optional[typing.Sequence[SipTrunkCreateRequestAllowedIpsItem]],
                    direction="write",
                ),
                "didinfo_enabled": didinfo_enabled,
                "call_restrict": call_restrict,
                "call_limit": call_limit,
                "cost_limit": cost_limit,
                "max_call_cost": max_call_cost,
                "channels_restrict": channels_restrict,
                "max_channels": max_channels,
                "rewrite_enabled": rewrite_enabled,
                "rewrite_prefix": rewrite_prefix,
                "rewrite_cond": rewrite_cond,
                "call_recording_enabled": call_recording_enabled,
                "transcription_enabled": transcription_enabled,
                "transcription_threshold": transcription_threshold,
                "machine_detection_enabled": machine_detection_enabled,
                "encrypted_media": encrypted_media,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SipTrunkResponse,
                    parse_obj_as(
                        type_=SipTrunkResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        UnauthorizedErrorResponse,
                        parse_obj_as(
                            type_=UnauthorizedErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def delete(
        self, id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[SuccessResponse]:
        """
        Deletes the SIP trunk identified by `id`. Deletion is permanent and stops call routing through the trunk.

        Parameters
        ----------
        id : int
            The unique ID of the SIP trunk.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[SuccessResponse]
            Returns a success confirmation. The SIP trunk is deleted.
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/trunks/{encode_path_param(id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SuccessResponse,
                    parse_obj_as(
                        type_=SuccessResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        UnauthorizedErrorResponse,
                        parse_obj_as(
                            type_=UnauthorizedErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawSipTrunksClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list(
        self,
        *,
        page: typing.Optional[int] = None,
        per_page: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[SipTrunkListResponse]:
        """
        Returns a paginated list of SIP trunks for the authenticated account.

        Parameters
        ----------
        page : typing.Optional[int]
            Page number to retrieve. Default `1`.

        per_page : typing.Optional[int]
            Number of records to return per page. Default `25`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[SipTrunkListResponse]
            Returns a paginated list of SIP trunks.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/trunks",
            method="GET",
            params={
                "page": page,
                "per_page": per_page,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SipTrunkListResponse,
                    parse_obj_as(
                        type_=SipTrunkListResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        UnauthorizedErrorResponse,
                        parse_obj_as(
                            type_=UnauthorizedErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def create(
        self,
        *,
        label: str,
        password: str,
        callerid: str,
        ip_restrict: bool,
        didinfo_enabled: bool,
        call_restrict: bool,
        channels_restrict: bool,
        rewrite_enabled: bool,
        transcription_enabled: bool,
        transcription_threshold: int,
        host_request: typing.Optional[SipTrunkCreateRequestHostRequest] = OMIT,
        multiple_numbers: typing.Optional[bool] = OMIT,
        allowed_ips: typing.Optional[typing.Sequence[SipTrunkCreateRequestAllowedIpsItem]] = OMIT,
        call_limit: typing.Optional[int] = OMIT,
        cost_limit: typing.Optional[bool] = OMIT,
        max_call_cost: typing.Optional[float] = OMIT,
        max_channels: typing.Optional[int] = OMIT,
        rewrite_prefix: typing.Optional[str] = OMIT,
        rewrite_cond: typing.Optional[str] = OMIT,
        call_recording_enabled: typing.Optional[bool] = OMIT,
        machine_detection_enabled: typing.Optional[bool] = OMIT,
        encrypted_media: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[SipTrunkResponse]:
        """
        Creates a SIP trunk for routing inbound and outbound calls. Returns the trunk with its generated `access_token`.

        Parameters
        ----------
        label : str
            User-defined name of the SIP trunk

        password : str
            Password set for the SIP trunk. A strong password helps keep the trunk secure.

        callerid : str
            Caller ID associated with the SIP trunk. Must be an active or verified number on the account.

        ip_restrict : bool
            Indicates whether SIP trunk registration is allowed from only specific public static IP addresses. When set to `true`, the `allowed_ips` parameter must be provided.

        didinfo_enabled : bool
            Indicates whether inbound calls include dialed number information in the `To` header of SIP INVITE requests

        call_restrict : bool
            Indicates whether a maximum call duration limit is enforced for the SIP trunk

        channels_restrict : bool
            Indicates whether a limit on the number of concurrent outbound calls is enforced for the SIP trunk

        rewrite_enabled : bool
            Indicates whether a custom dial plan is activated for the SIP trunk

        transcription_enabled : bool
            Indicates whether automatic call transcription is enabled for the SIP trunk.
            Available for `Flex Pro` customers only.

        transcription_threshold : int
            Transcriptions will be generated for calls that meet or exceed the specified minimal call duration threshold, in seconds.
            Available for `Flex Pro` customers only.

        host_request : typing.Optional[SipTrunkCreateRequestHostRequest]
            For SIP trunks with IP authentication, includes the SIP endpoint public static IP address and the status of the authentication request. Wavix authenticates all SIP traffic originating from this IP address.

        multiple_numbers : typing.Optional[bool]
            Indicates whether any active or verified phone number on the account can be used as the Caller ID for the SIP trunk.

        allowed_ips : typing.Optional[typing.Sequence[SipTrunkCreateRequestAllowedIpsItem]]
            A list of public static IP addresses allowed to register with the SIP trunk

        call_limit : typing.Optional[int]
            Maximum call duration for the SIP trunk, in seconds. Must not exceed the maximum duration set for the account. Ignored when `call_restrict` is `false`.

        cost_limit : typing.Optional[bool]
            Indicates if the max cost limit for an outbound call limit is activated for the SIP trunk.

        max_call_cost : typing.Optional[float]
            Maximum cost for an outbound call, in USD

        max_channels : typing.Optional[int]
            Maximum number of concurrent outbound calls for the SIP trunk. Must not exceed the outbound channel capacity set for the account. Ignored when `channels_restrict` is `false`.

        rewrite_prefix : typing.Optional[str]
            Digits to automatically prepend to each dialed phone number

        rewrite_cond : typing.Optional[str]
            Number of leading digits to automatically remove from each dialed phone number

        call_recording_enabled : typing.Optional[bool]
            Indicates whether outbound call recording is enabled for the SIP trunk

        machine_detection_enabled : typing.Optional[bool]
            Indicates whether automatic voicemail detection is enabled for the SIP trunk.
            Available for `Flex Pro` customers only.

        encrypted_media : typing.Optional[bool]
            Indicates whether SRTP media encryption is enabled for the SIP trunk.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[SipTrunkResponse]
            Returns the created SIP trunk.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/trunks",
            method="POST",
            json={
                "label": label,
                "password": password,
                "host_request": convert_and_respect_annotation_metadata(
                    object_=host_request, annotation=SipTrunkCreateRequestHostRequest, direction="write"
                ),
                "callerid": callerid,
                "multiple_numbers": multiple_numbers,
                "ip_restrict": ip_restrict,
                "allowed_ips": convert_and_respect_annotation_metadata(
                    object_=allowed_ips,
                    annotation=typing.Optional[typing.Sequence[SipTrunkCreateRequestAllowedIpsItem]],
                    direction="write",
                ),
                "didinfo_enabled": didinfo_enabled,
                "call_restrict": call_restrict,
                "call_limit": call_limit,
                "cost_limit": cost_limit,
                "max_call_cost": max_call_cost,
                "channels_restrict": channels_restrict,
                "max_channels": max_channels,
                "rewrite_enabled": rewrite_enabled,
                "rewrite_prefix": rewrite_prefix,
                "rewrite_cond": rewrite_cond,
                "call_recording_enabled": call_recording_enabled,
                "transcription_enabled": transcription_enabled,
                "transcription_threshold": transcription_threshold,
                "machine_detection_enabled": machine_detection_enabled,
                "encrypted_media": encrypted_media,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SipTrunkResponse,
                    parse_obj_as(
                        type_=SipTrunkResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        UnauthorizedErrorResponse,
                        parse_obj_as(
                            type_=UnauthorizedErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get(
        self, id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[SipTrunkResponse]:
        """
        Returns the SIP trunk identified by `id`.

        Parameters
        ----------
        id : int
            The unique ID of the SIP trunk.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[SipTrunkResponse]
            Returns the SIP trunk.
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/trunks/{encode_path_param(id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SipTrunkResponse,
                    parse_obj_as(
                        type_=SipTrunkResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        UnauthorizedErrorResponse,
                        parse_obj_as(
                            type_=UnauthorizedErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def update(
        self,
        id: int,
        *,
        label: str,
        password: str,
        callerid: str,
        ip_restrict: bool,
        didinfo_enabled: bool,
        call_restrict: bool,
        channels_restrict: bool,
        rewrite_enabled: bool,
        transcription_enabled: bool,
        transcription_threshold: int,
        host_request: typing.Optional[SipTrunkCreateRequestHostRequest] = OMIT,
        multiple_numbers: typing.Optional[bool] = OMIT,
        allowed_ips: typing.Optional[typing.Sequence[SipTrunkCreateRequestAllowedIpsItem]] = OMIT,
        call_limit: typing.Optional[int] = OMIT,
        cost_limit: typing.Optional[bool] = OMIT,
        max_call_cost: typing.Optional[float] = OMIT,
        max_channels: typing.Optional[int] = OMIT,
        rewrite_prefix: typing.Optional[str] = OMIT,
        rewrite_cond: typing.Optional[str] = OMIT,
        call_recording_enabled: typing.Optional[bool] = OMIT,
        machine_detection_enabled: typing.Optional[bool] = OMIT,
        encrypted_media: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[SipTrunkResponse]:
        """
        Replaces the configuration of the SIP trunk identified by `id`. Omitted fields revert to their defaults.

        Parameters
        ----------
        id : int
            The unique ID of the SIP trunk.

        label : str
            User-defined name of the SIP trunk

        password : str
            Password set for the SIP trunk. A strong password helps keep the trunk secure.

        callerid : str
            Caller ID associated with the SIP trunk. Must be an active or verified number on the account.

        ip_restrict : bool
            Indicates whether SIP trunk registration is allowed from only specific public static IP addresses. When set to `true`, the `allowed_ips` parameter must be provided.

        didinfo_enabled : bool
            Indicates whether inbound calls include dialed number information in the `To` header of SIP INVITE requests

        call_restrict : bool
            Indicates whether a maximum call duration limit is enforced for the SIP trunk

        channels_restrict : bool
            Indicates whether a limit on the number of concurrent outbound calls is enforced for the SIP trunk

        rewrite_enabled : bool
            Indicates whether a custom dial plan is activated for the SIP trunk

        transcription_enabled : bool
            Indicates whether automatic call transcription is enabled for the SIP trunk.
            Available for `Flex Pro` customers only.

        transcription_threshold : int
            Transcriptions will be generated for calls that meet or exceed the specified minimal call duration threshold, in seconds.
            Available for `Flex Pro` customers only.

        host_request : typing.Optional[SipTrunkCreateRequestHostRequest]
            For SIP trunks with IP authentication, includes the SIP endpoint public static IP address and the status of the authentication request. Wavix authenticates all SIP traffic originating from this IP address.

        multiple_numbers : typing.Optional[bool]
            Indicates whether any active or verified phone number on the account can be used as the Caller ID for the SIP trunk.

        allowed_ips : typing.Optional[typing.Sequence[SipTrunkCreateRequestAllowedIpsItem]]
            A list of public static IP addresses allowed to register with the SIP trunk

        call_limit : typing.Optional[int]
            Maximum call duration for the SIP trunk, in seconds. Must not exceed the maximum duration set for the account. Ignored when `call_restrict` is `false`.

        cost_limit : typing.Optional[bool]
            Indicates if the max cost limit for an outbound call limit is activated for the SIP trunk.

        max_call_cost : typing.Optional[float]
            Maximum cost for an outbound call, in USD

        max_channels : typing.Optional[int]
            Maximum number of concurrent outbound calls for the SIP trunk. Must not exceed the outbound channel capacity set for the account. Ignored when `channels_restrict` is `false`.

        rewrite_prefix : typing.Optional[str]
            Digits to automatically prepend to each dialed phone number

        rewrite_cond : typing.Optional[str]
            Number of leading digits to automatically remove from each dialed phone number

        call_recording_enabled : typing.Optional[bool]
            Indicates whether outbound call recording is enabled for the SIP trunk

        machine_detection_enabled : typing.Optional[bool]
            Indicates whether automatic voicemail detection is enabled for the SIP trunk.
            Available for `Flex Pro` customers only.

        encrypted_media : typing.Optional[bool]
            Indicates whether SRTP media encryption is enabled for the SIP trunk.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[SipTrunkResponse]
            Returns the updated SIP trunk.
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/trunks/{encode_path_param(id)}",
            method="PUT",
            json={
                "label": label,
                "password": password,
                "host_request": convert_and_respect_annotation_metadata(
                    object_=host_request, annotation=SipTrunkCreateRequestHostRequest, direction="write"
                ),
                "callerid": callerid,
                "multiple_numbers": multiple_numbers,
                "ip_restrict": ip_restrict,
                "allowed_ips": convert_and_respect_annotation_metadata(
                    object_=allowed_ips,
                    annotation=typing.Optional[typing.Sequence[SipTrunkCreateRequestAllowedIpsItem]],
                    direction="write",
                ),
                "didinfo_enabled": didinfo_enabled,
                "call_restrict": call_restrict,
                "call_limit": call_limit,
                "cost_limit": cost_limit,
                "max_call_cost": max_call_cost,
                "channels_restrict": channels_restrict,
                "max_channels": max_channels,
                "rewrite_enabled": rewrite_enabled,
                "rewrite_prefix": rewrite_prefix,
                "rewrite_cond": rewrite_cond,
                "call_recording_enabled": call_recording_enabled,
                "transcription_enabled": transcription_enabled,
                "transcription_threshold": transcription_threshold,
                "machine_detection_enabled": machine_detection_enabled,
                "encrypted_media": encrypted_media,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SipTrunkResponse,
                    parse_obj_as(
                        type_=SipTrunkResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        UnauthorizedErrorResponse,
                        parse_obj_as(
                            type_=UnauthorizedErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def delete(
        self, id: int, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[SuccessResponse]:
        """
        Deletes the SIP trunk identified by `id`. Deletion is permanent and stops call routing through the trunk.

        Parameters
        ----------
        id : int
            The unique ID of the SIP trunk.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[SuccessResponse]
            Returns a success confirmation. The SIP trunk is deleted.
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/trunks/{encode_path_param(id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SuccessResponse,
                    parse_obj_as(
                        type_=SuccessResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        UnauthorizedErrorResponse,
                        parse_obj_as(
                            type_=UnauthorizedErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
