# This file was auto-generated by Fern from our API Definition.

import typing

GetBrandsResponseStatus = typing.Union[
    typing.Literal["REVIEW", "VERIFIED", "UNVERIFIED", "VETTED_VERIFIED", "SUSPENDED"], typing.Any
]
