# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from .raw_client import AsyncRawBuyClient, RawBuyClient

if typing.TYPE_CHECKING:
    from .cities.client import AsyncCitiesClient, CitiesClient
    from .countries.client import AsyncCountriesClient, CountriesClient
    from .numbers.client import AsyncNumbersClient, NumbersClient
    from .region_cities.client import AsyncRegionCitiesClient, RegionCitiesClient
    from .regions.client import AsyncRegionsClient, RegionsClient


class BuyClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawBuyClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._countries: typing.Optional[CountriesClient] = None
        self._regions: typing.Optional[RegionsClient] = None
        self._cities: typing.Optional[CitiesClient] = None
        self._region_cities: typing.Optional[RegionCitiesClient] = None
        self._numbers: typing.Optional[NumbersClient] = None

    @property
    def with_raw_response(self) -> RawBuyClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawBuyClient
        """
        return self._raw_client

    @property
    def countries(self):
        if self._countries is None:
            from .countries.client import CountriesClient  # noqa: E402

            self._countries = CountriesClient(client_wrapper=self._client_wrapper)
        return self._countries

    @property
    def regions(self):
        if self._regions is None:
            from .regions.client import RegionsClient  # noqa: E402

            self._regions = RegionsClient(client_wrapper=self._client_wrapper)
        return self._regions

    @property
    def cities(self):
        if self._cities is None:
            from .cities.client import CitiesClient  # noqa: E402

            self._cities = CitiesClient(client_wrapper=self._client_wrapper)
        return self._cities

    @property
    def region_cities(self):
        if self._region_cities is None:
            from .region_cities.client import RegionCitiesClient  # noqa: E402

            self._region_cities = RegionCitiesClient(client_wrapper=self._client_wrapper)
        return self._region_cities

    @property
    def numbers(self):
        if self._numbers is None:
            from .numbers.client import NumbersClient  # noqa: E402

            self._numbers = NumbersClient(client_wrapper=self._client_wrapper)
        return self._numbers


class AsyncBuyClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawBuyClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._countries: typing.Optional[AsyncCountriesClient] = None
        self._regions: typing.Optional[AsyncRegionsClient] = None
        self._cities: typing.Optional[AsyncCitiesClient] = None
        self._region_cities: typing.Optional[AsyncRegionCitiesClient] = None
        self._numbers: typing.Optional[AsyncNumbersClient] = None

    @property
    def with_raw_response(self) -> AsyncRawBuyClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawBuyClient
        """
        return self._raw_client

    @property
    def countries(self):
        if self._countries is None:
            from .countries.client import AsyncCountriesClient  # noqa: E402

            self._countries = AsyncCountriesClient(client_wrapper=self._client_wrapper)
        return self._countries

    @property
    def regions(self):
        if self._regions is None:
            from .regions.client import AsyncRegionsClient  # noqa: E402

            self._regions = AsyncRegionsClient(client_wrapper=self._client_wrapper)
        return self._regions

    @property
    def cities(self):
        if self._cities is None:
            from .cities.client import AsyncCitiesClient  # noqa: E402

            self._cities = AsyncCitiesClient(client_wrapper=self._client_wrapper)
        return self._cities

    @property
    def region_cities(self):
        if self._region_cities is None:
            from .region_cities.client import AsyncRegionCitiesClient  # noqa: E402

            self._region_cities = AsyncRegionCitiesClient(client_wrapper=self._client_wrapper)
        return self._region_cities

    @property
    def numbers(self):
        if self._numbers is None:
            from .numbers.client import AsyncNumbersClient  # noqa: E402

            self._numbers = AsyncNumbersClient(client_wrapper=self._client_wrapper)
        return self._numbers
