# This file was auto-generated by Fern from our API Definition.

import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from ...types.city_list_response import CityListResponse
from .raw_client import AsyncRawRegionCitiesClient, RawRegionCitiesClient


class RegionCitiesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawRegionCitiesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawRegionCitiesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawRegionCitiesClient
        """
        return self._raw_client

    def list(
        self,
        country_id: int,
        region_id: int,
        *,
        text_enabled_only: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CityListResponse:
        """
        Returns a list of cities in the specified region for countries where `has_provinces_or_states` is `true`.

        Parameters
        ----------
        country_id : int
            The unique ID of the country.

        region_id : int
            The unique ID of the region.

        text_enabled_only : typing.Optional[bool]
            When `true`, returns only cities that offer text-enabled numbers.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CityListResponse
            Returns the list of cities.

        Examples
        --------
        from wavix import Wavix

        client = Wavix(
            token="YOUR_TOKEN",
        )
        client.buy.region_cities.list(
            country_id=1891,
            region_id=821,
        )
        """
        _response = self._raw_client.list(
            country_id, region_id, text_enabled_only=text_enabled_only, request_options=request_options
        )
        return _response.data


class AsyncRegionCitiesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawRegionCitiesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawRegionCitiesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawRegionCitiesClient
        """
        return self._raw_client

    async def list(
        self,
        country_id: int,
        region_id: int,
        *,
        text_enabled_only: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CityListResponse:
        """
        Returns a list of cities in the specified region for countries where `has_provinces_or_states` is `true`.

        Parameters
        ----------
        country_id : int
            The unique ID of the country.

        region_id : int
            The unique ID of the region.

        text_enabled_only : typing.Optional[bool]
            When `true`, returns only cities that offer text-enabled numbers.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CityListResponse
            Returns the list of cities.

        Examples
        --------
        import asyncio

        from wavix import AsyncWavix

        client = AsyncWavix(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.buy.region_cities.list(
                country_id=1891,
                region_id=821,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list(
            country_id, region_id, text_enabled_only=text_enabled_only, request_options=request_options
        )
        return _response.data
