# This file was auto-generated by Fern from our API Definition.

import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from ...types.success_response import SuccessResponse
from ...types.two_factor_verification_check_response import TwoFactorVerificationCheckResponse
from ...types.two_factor_verification_resend_response import TwoFactorVerificationResendResponse
from ...types.two_factor_verification_response import TwoFactorVerificationResponse
from .raw_client import AsyncRawVerificationClient, RawVerificationClient
from .types.two_factor_verification_resend_request_channel import TwoFactorVerificationResendRequestChannel

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class VerificationClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawVerificationClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawVerificationClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawVerificationClient
        """
        return self._raw_client

    def create(
        self, *, service_id: str, to: str, channel: str, request_options: typing.Optional[RequestOptions] = None
    ) -> TwoFactorVerificationResponse:
        """
        Creates a 2FA verification and sends a real one-time password (OTP) to the destination phone number over the selected channel; this bills the account per OTP sent. Requires a 2FA service configured in the Wavix portal; the service is reused to generate and validate OTPs.

        The verification proceeds through three steps:
        1. Create a verification to generate and send an OTP.
        2. Resend the OTP on the same verification if needed.
        3. Validate the OTP through the check endpoint.

        Parameters
        ----------
        service_id : str
            Unique Wavix 2FA Service ID. Available on the Wavix portal.

        to : str
            End user's phone number to which the verification code will be sent. The phone number must be in E.164 format.

        channel : str
            Channel used to deliver the verification code. One of `sms` (sent as a text message) or `voice` (read aloud over a phone call).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TwoFactorVerificationResponse
            Returns the created 2FA verification.

        Examples
        --------
        from wavix import Wavix

        client = Wavix(
            token="YOUR_TOKEN",
        )
        client.two_fa.verification.create(
            service_id="7204a030201211ee9fb47d093f2f127c",
            to="447919433768",
            channel="sms",
        )
        """
        _response = self._raw_client.create(
            service_id=service_id, to=to, channel=channel, request_options=request_options
        )
        return _response.data

    def resend(
        self,
        session_id: str,
        *,
        channel: TwoFactorVerificationResendRequestChannel,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TwoFactorVerificationResendResponse:
        """
        Resends the OTP for the verification identified by `session_id` over the specified channel. Previously sent codes are invalidated.

        Parameters
        ----------
        session_id : str
            The unique ID of the 2FA verification session.

        channel : TwoFactorVerificationResendRequestChannel
            Channel used to resend the verification code. One of `sms` (sent as a text message) or `voice` (read aloud over a phone call).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TwoFactorVerificationResendResponse
            Returns the resend result, including the channel used.

        Examples
        --------
        from wavix import Wavix

        client = Wavix(
            token="YOUR_TOKEN",
        )
        client.two_fa.verification.resend(
            session_id="2953d4308f2e11ecb75fcdafd6d2d687",
            channel="sms",
        )
        """
        _response = self._raw_client.resend(session_id, channel=channel, request_options=request_options)
        return _response.data

    def check(
        self, session_id: str, *, code: str, request_options: typing.Optional[RequestOptions] = None
    ) -> TwoFactorVerificationCheckResponse:
        """
        Validates the OTP submitted by the end user against the verification identified by `session_id`. Non-idempotent — each call consumes one of a limited number of attempts tracked server-side; once exhausted, the verification returns `429` until a new verification is created.

        Parameters
        ----------
        session_id : str
            The unique ID of the 2FA verification session.

        code : str
            The code entered by an end user

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TwoFactorVerificationCheckResponse
            Returns the validation result in `is_valid`.

        Examples
        --------
        from wavix import Wavix

        client = Wavix(
            token="YOUR_TOKEN",
        )
        client.two_fa.verification.check(
            session_id="2953d4308f2e11ecb75fcdafd6d2d687",
            code="123456",
        )
        """
        _response = self._raw_client.check(session_id, code=code, request_options=request_options)
        return _response.data

    def cancel(self, session_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> SuccessResponse:
        """
        Cancels the 2FA verification identified by `session_id`. No further codes are sent, and previously sent codes can no longer be validated. A new verification is required to send another code.

        Parameters
        ----------
        session_id : str
            The unique ID of the 2FA verification session.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SuccessResponse
            Returns a success confirmation. The verification is canceled.

        Examples
        --------
        from wavix import Wavix

        client = Wavix(
            token="YOUR_TOKEN",
        )
        client.two_fa.verification.cancel(
            session_id="2953d4308f2e11ecb75fcdafd6d2d687",
        )
        """
        _response = self._raw_client.cancel(session_id, request_options=request_options)
        return _response.data


class AsyncVerificationClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawVerificationClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawVerificationClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawVerificationClient
        """
        return self._raw_client

    async def create(
        self, *, service_id: str, to: str, channel: str, request_options: typing.Optional[RequestOptions] = None
    ) -> TwoFactorVerificationResponse:
        """
        Creates a 2FA verification and sends a real one-time password (OTP) to the destination phone number over the selected channel; this bills the account per OTP sent. Requires a 2FA service configured in the Wavix portal; the service is reused to generate and validate OTPs.

        The verification proceeds through three steps:
        1. Create a verification to generate and send an OTP.
        2. Resend the OTP on the same verification if needed.
        3. Validate the OTP through the check endpoint.

        Parameters
        ----------
        service_id : str
            Unique Wavix 2FA Service ID. Available on the Wavix portal.

        to : str
            End user's phone number to which the verification code will be sent. The phone number must be in E.164 format.

        channel : str
            Channel used to deliver the verification code. One of `sms` (sent as a text message) or `voice` (read aloud over a phone call).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TwoFactorVerificationResponse
            Returns the created 2FA verification.

        Examples
        --------
        import asyncio

        from wavix import AsyncWavix

        client = AsyncWavix(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.two_fa.verification.create(
                service_id="7204a030201211ee9fb47d093f2f127c",
                to="447919433768",
                channel="sms",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(
            service_id=service_id, to=to, channel=channel, request_options=request_options
        )
        return _response.data

    async def resend(
        self,
        session_id: str,
        *,
        channel: TwoFactorVerificationResendRequestChannel,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> TwoFactorVerificationResendResponse:
        """
        Resends the OTP for the verification identified by `session_id` over the specified channel. Previously sent codes are invalidated.

        Parameters
        ----------
        session_id : str
            The unique ID of the 2FA verification session.

        channel : TwoFactorVerificationResendRequestChannel
            Channel used to resend the verification code. One of `sms` (sent as a text message) or `voice` (read aloud over a phone call).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TwoFactorVerificationResendResponse
            Returns the resend result, including the channel used.

        Examples
        --------
        import asyncio

        from wavix import AsyncWavix

        client = AsyncWavix(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.two_fa.verification.resend(
                session_id="2953d4308f2e11ecb75fcdafd6d2d687",
                channel="sms",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.resend(session_id, channel=channel, request_options=request_options)
        return _response.data

    async def check(
        self, session_id: str, *, code: str, request_options: typing.Optional[RequestOptions] = None
    ) -> TwoFactorVerificationCheckResponse:
        """
        Validates the OTP submitted by the end user against the verification identified by `session_id`. Non-idempotent — each call consumes one of a limited number of attempts tracked server-side; once exhausted, the verification returns `429` until a new verification is created.

        Parameters
        ----------
        session_id : str
            The unique ID of the 2FA verification session.

        code : str
            The code entered by an end user

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        TwoFactorVerificationCheckResponse
            Returns the validation result in `is_valid`.

        Examples
        --------
        import asyncio

        from wavix import AsyncWavix

        client = AsyncWavix(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.two_fa.verification.check(
                session_id="2953d4308f2e11ecb75fcdafd6d2d687",
                code="123456",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.check(session_id, code=code, request_options=request_options)
        return _response.data

    async def cancel(
        self, session_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> SuccessResponse:
        """
        Cancels the 2FA verification identified by `session_id`. No further codes are sent, and previously sent codes can no longer be validated. A new verification is required to send another code.

        Parameters
        ----------
        session_id : str
            The unique ID of the 2FA verification session.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SuccessResponse
            Returns a success confirmation. The verification is canceled.

        Examples
        --------
        import asyncio

        from wavix import AsyncWavix

        client = AsyncWavix(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.two_fa.verification.cancel(
                session_id="2953d4308f2e11ecb75fcdafd6d2d687",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.cancel(session_id, request_options=request_options)
        return _response.data
