# This file was auto-generated by Fern from our API Definition.

import typing

from ... import core
from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from ...types.document_type_id import DocumentTypeId
from ...types.number_document import NumberDocument
from .raw_client import AsyncRawPapersClient, RawPapersClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class PapersClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawPapersClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawPapersClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawPapersClient
        """
        return self._raw_client

    def upload(
        self,
        *,
        did_ids: str,
        doc_attachment: core.File,
        doc_id: DocumentTypeId,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[NumberDocument]:
        """
        Uploads a verification document for one or more phone numbers.
        Uploaded files must meet the following requirements:
        - Allowed formats: PNG, JPG, JPEG, TIFF, BMP, or PDF
        - Maximum file size: 10 MB
        - Files can't be password protected
        - PDF files must not contain digital signatures

        Parameters
        ----------
        did_ids : str
            Comma-separated record IDs of the phone numbers the document applies to.

        doc_attachment : core.File
            See core.File for more documentation

        doc_id : DocumentTypeId

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[NumberDocument]
            Returns the uploaded documents and their review status.

        Examples
        --------
        from wavix import Wavix

        client = Wavix(
            token="YOUR_TOKEN",
        )
        client.numbers.papers.upload(
            did_ids="did_ids",
            doc_id=1,
        )
        """
        _response = self._raw_client.upload(
            did_ids=did_ids, doc_attachment=doc_attachment, doc_id=doc_id, request_options=request_options
        )
        return _response.data


class AsyncPapersClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawPapersClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawPapersClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawPapersClient
        """
        return self._raw_client

    async def upload(
        self,
        *,
        did_ids: str,
        doc_attachment: core.File,
        doc_id: DocumentTypeId,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[NumberDocument]:
        """
        Uploads a verification document for one or more phone numbers.
        Uploaded files must meet the following requirements:
        - Allowed formats: PNG, JPG, JPEG, TIFF, BMP, or PDF
        - Maximum file size: 10 MB
        - Files can't be password protected
        - PDF files must not contain digital signatures

        Parameters
        ----------
        did_ids : str
            Comma-separated record IDs of the phone numbers the document applies to.

        doc_attachment : core.File
            See core.File for more documentation

        doc_id : DocumentTypeId

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[NumberDocument]
            Returns the uploaded documents and their review status.

        Examples
        --------
        import asyncio

        from wavix import AsyncWavix

        client = AsyncWavix(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.numbers.papers.upload(
                did_ids="did_ids",
                doc_id=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.upload(
            did_ids=did_ids, doc_attachment=doc_attachment, doc_id=doc_id, request_options=request_options
        )
        return _response.data
