# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from ...types.list_sessions_response_item import ListSessionsResponseItem
from .raw_client import AsyncRawSessionsClient, RawSessionsClient


class SessionsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawSessionsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawSessionsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawSessionsClient
        """
        return self._raw_client

    def list(
        self, service_id: str, *, from_: dt.date, to: dt.date, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[ListSessionsResponseItem]:
        """
        Returns the 2FA verifications for the service identified by `service_id`, within the requested date range.

        Parameters
        ----------
        service_id : str
            The unique ID of the 2FA service.

        from_ : dt.date
            Start of the date range to query, in `YYYY-MM-DD` format. Inclusive.

        to : dt.date
            End of the date range to query, in `YYYY-MM-DD` format. Inclusive.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[ListSessionsResponseItem]
            Returns the list of 2FA verifications.

        Examples
        --------
        import datetime

        from wavix import Wavix

        client = Wavix(
            token="YOUR_TOKEN",
        )
        client.two_fa.sessions.list(
            service_id="7204a030201211ee9fb47d093f2f127c",
            from_=datetime.date.fromisoformat(
                "2022-01-01",
            ),
            to=datetime.date.fromisoformat(
                "2022-01-31",
            ),
        )
        """
        _response = self._raw_client.list(service_id, from_=from_, to=to, request_options=request_options)
        return _response.data


class AsyncSessionsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawSessionsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawSessionsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawSessionsClient
        """
        return self._raw_client

    async def list(
        self, service_id: str, *, from_: dt.date, to: dt.date, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[ListSessionsResponseItem]:
        """
        Returns the 2FA verifications for the service identified by `service_id`, within the requested date range.

        Parameters
        ----------
        service_id : str
            The unique ID of the 2FA service.

        from_ : dt.date
            Start of the date range to query, in `YYYY-MM-DD` format. Inclusive.

        to : dt.date
            End of the date range to query, in `YYYY-MM-DD` format. Inclusive.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[ListSessionsResponseItem]
            Returns the list of 2FA verifications.

        Examples
        --------
        import asyncio
        import datetime

        from wavix import AsyncWavix

        client = AsyncWavix(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.two_fa.sessions.list(
                service_id="7204a030201211ee9fb47d093f2f127c",
                from_=datetime.date.fromisoformat(
                    "2022-01-01",
                ),
                to=datetime.date.fromisoformat(
                    "2022-01-31",
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list(service_id, from_=from_, to=to, request_options=request_options)
        return _response.data
