# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.call_webhook import CallWebhook
from ..types.call_webhook_list_response import CallWebhookListResponse
from ..types.success_response import SuccessResponse
from .raw_client import AsyncRawCallWebhooksClient, RawCallWebhooksClient
from .types.call_webhooks_create_request_event_type import CallWebhooksCreateRequestEventType
from .types.delete_call_webhooks_request_event_type import DeleteCallWebhooksRequestEventType

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class CallWebhooksClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawCallWebhooksClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawCallWebhooksClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawCallWebhooksClient
        """
        return self._raw_client

    def list(self, *, request_options: typing.Optional[RequestOptions] = None) -> CallWebhookListResponse:
        """
        Returns the configured call webhooks for the authenticated account. Wavix sends POST callbacks for `on-call` and `post-call` events.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CallWebhookListResponse
            Returns the list of call webhooks.

        Examples
        --------
        from wavix import Wavix

        client = Wavix(
            token="YOUR_TOKEN",
        )
        client.call_webhooks.list()
        """
        _response = self._raw_client.list(request_options=request_options)
        return _response.data

    def create(
        self,
        *,
        url: str,
        event_type: CallWebhooksCreateRequestEventType,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CallWebhook:
        """
        Registers a callback URL for the `on-call` or `post-call` event. Wavix sends a POST callback to the URL when the event occurs.

        Parameters
        ----------
        url : str
            Webhook URL to send call events to.

        event_type : CallWebhooksCreateRequestEventType
            Allowed values: `on-call`, `post-call`.
             - `on-call`: Sends real-time status updates
              when a call starts, is answered, and ends.

             - `post-call`: Sends a callback after the call ends
              with disposition, duration, and cost.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CallWebhook
            Returns the created call webhook.

        Examples
        --------
        from wavix import Wavix

        client = Wavix(
            token="YOUR_TOKEN",
        )
        client.call_webhooks.create(
            url="https://you-site.com/webhook",
            event_type="post-call",
        )
        """
        _response = self._raw_client.create(url=url, event_type=event_type, request_options=request_options)
        return _response.data

    def delete(
        self, *, event_type: DeleteCallWebhooksRequestEventType, request_options: typing.Optional[RequestOptions] = None
    ) -> SuccessResponse:
        """
        Removes the call webhook for the given event type. Wavix stops sending callbacks for that event.

        Parameters
        ----------
        event_type : DeleteCallWebhooksRequestEventType
            Event type of the webhook to delete. One of `post-call` (callbacks sent after a call ends) or `on-call` (real-time call status callbacks during a call).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SuccessResponse
            Returns a success confirmation. The call webhook is removed.

        Examples
        --------
        from wavix import Wavix

        client = Wavix(
            token="YOUR_TOKEN",
        )
        client.call_webhooks.delete(
            event_type="post-call",
        )
        """
        _response = self._raw_client.delete(event_type=event_type, request_options=request_options)
        return _response.data


class AsyncCallWebhooksClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawCallWebhooksClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawCallWebhooksClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawCallWebhooksClient
        """
        return self._raw_client

    async def list(self, *, request_options: typing.Optional[RequestOptions] = None) -> CallWebhookListResponse:
        """
        Returns the configured call webhooks for the authenticated account. Wavix sends POST callbacks for `on-call` and `post-call` events.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CallWebhookListResponse
            Returns the list of call webhooks.

        Examples
        --------
        import asyncio

        from wavix import AsyncWavix

        client = AsyncWavix(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.call_webhooks.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(request_options=request_options)
        return _response.data

    async def create(
        self,
        *,
        url: str,
        event_type: CallWebhooksCreateRequestEventType,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CallWebhook:
        """
        Registers a callback URL for the `on-call` or `post-call` event. Wavix sends a POST callback to the URL when the event occurs.

        Parameters
        ----------
        url : str
            Webhook URL to send call events to.

        event_type : CallWebhooksCreateRequestEventType
            Allowed values: `on-call`, `post-call`.
             - `on-call`: Sends real-time status updates
              when a call starts, is answered, and ends.

             - `post-call`: Sends a callback after the call ends
              with disposition, duration, and cost.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CallWebhook
            Returns the created call webhook.

        Examples
        --------
        import asyncio

        from wavix import AsyncWavix

        client = AsyncWavix(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.call_webhooks.create(
                url="https://you-site.com/webhook",
                event_type="post-call",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(url=url, event_type=event_type, request_options=request_options)
        return _response.data

    async def delete(
        self, *, event_type: DeleteCallWebhooksRequestEventType, request_options: typing.Optional[RequestOptions] = None
    ) -> SuccessResponse:
        """
        Removes the call webhook for the given event type. Wavix stops sending callbacks for that event.

        Parameters
        ----------
        event_type : DeleteCallWebhooksRequestEventType
            Event type of the webhook to delete. One of `post-call` (callbacks sent after a call ends) or `on-call` (real-time call status callbacks during a call).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SuccessResponse
            Returns a success confirmation. The call webhook is removed.

        Examples
        --------
        import asyncio

        from wavix import AsyncWavix

        client = AsyncWavix(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.call_webhooks.delete(
                event_type="post-call",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(event_type=event_type, request_options=request_options)
        return _response.data
